import './styles/base.css';
import './styles/editor.css';
import './styles/layout.css';
import './styles/sprint2-polish.css';
import './styles/sprint1-9.css';
import './styles/author-studio-2.css';
import './styles/settings-and-toolbar.css';
import { initApp } from './app.js';
import { installSprint19 } from './sprint1-9.js';
import { installTimelineInteractions } from './timeline-interactions.js';
import { installSettingsUI } from './settings-ui.js';
import { installToolbarEnhancements } from './toolbar-enhancements.js';
import './sprint2-polish.js';
import './author-studio-2.js';

initApp();
installSprint19();
installTimelineInteractions();
installSettingsUI();
installToolbarEnhancements();
