import { createDocument, getCurrentDocument, setCurrentDocument, updateDocumentContent, updateDocumentTitle } from './document.js';
import { saveProject, openProject, clearCurrentPath, saveAutosave, clearAutosave, hasAutosave, loadAutosave, listLibraryDocuments, loadLibraryDocument } from './filesystem.js';
import { countWords, countCharacters } from './statistics.js';

const AUTOSAVE_INTERVAL=10000;
const fonts=['Georgia','Times New Roman','Arial','Calibri','Garamond','Verdana','Tahoma','Trebuchet MS','Courier New','Lucida Console','Palatino Linotype','Book Antiqua','Cambria','Century Gothic','Consolas','Franklin Gothic Medium','Impact','Lucida Sans Unicode','Segoe UI','Gill Sans','Helvetica','Arial Black'];
const sizes=Array.from({length:56},(_,i)=>i+9);
const templates=[['Blank Document','document'],['Novel','novel'],['Novella','novella'],['Short Story','short-story'],['Screenplay','screenplay'],['Poetry','poetry']];
const palette=['#000000','#434343','#666666','#999999','#b7b7b7','#cccccc','#d9d9d9','#efefef','#f4cccc','#ea9999','#e06666','#cc0000','#990000','#660000','#e6b8af','#fce5cd','#f9cb9c','#f6b26b','#e69138','#b45f06','#783f04','#fff2cc','#ffe599','#ffd966','#f1c232','#bf9000','#7f6000','#d9ead3','#b6d7a8','#93c47d','#6aa84f','#38761d','#274e13','#d0e0e3','#a2c4c9','#76a5af','#45818e','#134f5c','#0b5394','#c9daf8','#a4c2f4','#6d9eeb','#3c78d8','#1155cc','#1c4587'];
const universalKey='scriptsmith-universal-library';

export function initApp(){
 const app=document.querySelector('#app');setCurrentDocument(createDocument());clearCurrentPath();let isDirty=false,autosaveBusy=false,activeChapter=null,activeTemplate=null;
 const universal=()=>{try{return JSON.parse(localStorage.getItem(universalKey)||'{"characters":[],"locations":[],"timeline":[]}')}catch(_){return {characters:[],locations:[],timeline:[]}}};
 const saveUniversal=x=>localStorage.setItem(universalKey,JSON.stringify(x));
 app.innerHTML=`<div class="home" id="home"><header class="home-header"><div class="brand"><span class="brand-mark">S</span><div><strong>ScriptSmith</strong><small>Writer's Studio</small></div></div><button id="home-settings" class="theme-button">Settings</button></header><main class="home-content"><section class="welcome"><h1>What will you write?</h1><p>Start something new or return to a project.</p><div class="template-grid" id="templates">${templates.map(([n,t])=>`<button class="template-card theme-card" data-template="${t}"><strong>${n}</strong><span>Start a new ${n.toLowerCase()}</span></button>`).join('')}</div></section><section class="library-section"><div class="section-heading"><div><h2>Your Library</h2><p>Your ScriptSmith projects stay available inside the app.</p></div><button id="home-open" class="theme-button">Open from computer</button></div><div class="universal-library"><button class="universal-card" id="universal-characters"><strong>Universal Characters</strong><span>Characters shared across your stories</span></button><button class="universal-card" id="universal-world"><strong>Universal World</strong><span>Locations and world details shared across your stories</span></button></div><div id="library" class="library-grid"><div class="library-empty">Loading your library…</div></div></section></main></div><div id="collection-shell" hidden></div><div id="editor-shell" hidden></div>`;
 async function refreshLibrary(){const el=document.querySelector('#library'),docs=await listLibraryDocuments();if(!docs.length){el.innerHTML='<div class="library-empty">No saved projects yet. Start a document above and save it.</div>';return;}el.innerHTML=docs.map(d=>`<button class="project-card theme-card" data-library-id="${d.libraryId||d.id}"><span class="project-icon">S</span><span><strong>${esc(d.title||'Untitled Document')}</strong><small>${date(d.libraryUpdatedAt||d.updatedAt)}</small></span></button>`).join('');el.querySelectorAll('.project-card').forEach(c=>c.onclick=async()=>{const d=docs.find(x=>(x.libraryId||x.id)===c.dataset.libraryId);if(d)await openDocument(await loadLibraryDocument(d));});}
 function showCollection(type){activeTemplate=type;document.querySelector('#home').hidden=true;document.querySelector('#editor-shell').hidden=true;const shell=document.querySelector('#collection-shell');shell.hidden=false;const names={document:'Documents',novel:'Novels',novella:'Novellas','short-story':'Short Stories',screenplay:'Screenplays',poetry:'Poems'};shell.innerHTML=`<header class="topbar"><div class="brand"><button id="collection-home" class="home-button theme-button">‹ Library</button><span class="brand-mark">S</span><div><strong>ScriptSmith</strong><small>${names[type]||'Writing'}</small></div></div><div></div><div class="top-actions"><button id="collection-new" class="primary-action">+ New ${names[type]||'Document'}</button></div></header><main class="collection-page"><div class="collection-heading"><h1>${names[type]||'Writing'}</h1><p>Your ${names[type]?.toLowerCase()||'writing pieces'} live here.</p></div><div id="collection-list" class="library-grid"></div></main>`;renderCollection(type);document.querySelector('#collection-home').onclick=()=>showHome();document.querySelector('#collection-new').onclick=()=>newDocument(type);}
 async function renderCollection(type){const docs=await listLibraryDocuments();const list=document.querySelector('#collection-list');if(!list)return;const filtered=docs.filter(d=>!type||type==='document'||d.type===type);list.innerHTML=filtered.length?filtered.map(d=>`<button class="project-card theme-card" data-library-id="${d.libraryId||d.id}"><span class="project-icon">S</span><span><strong>${esc(d.title||'Untitled')}</strong><small>${date(d.libraryUpdatedAt||d.updatedAt)}</small></span></button>`).join(''):'<div class="library-empty">Nothing here yet. Start your first piece above.</div>';list.querySelectorAll('.project-card').forEach(c=>c.onclick=async()=>{const d=filtered.find(x=>(x.libraryId||x.id)===c.dataset.libraryId);if(d)await openDocument(await loadLibraryDocument(d));});}
 function showHome(){document.querySelector('#collection-shell').hidden=true;document.querySelector('#editor-shell').hidden=true;document.querySelector('#home').hidden=false;closePalette();refreshLibrary();}
 function renderEditor(){document.querySelector('#home').hidden=true;document.querySelector('#collection-shell').hidden=true;const shell=document.querySelector('#editor-shell');shell.hidden=false;const d=getCurrentDocument();shell.innerHTML=`<header class="topbar"><div class="brand"><button id="back-home" class="home-button theme-button">‹ Library</button><span class="brand-mark">S</span><div><strong>ScriptSmith</strong><small>Writer's Studio</small></div></div><div class="document-title"><input id="title" value="${esc(d.title)}" aria-label="Document title"></div><div class="top-actions"><button id="new" class="theme-button">New</button><button id="open" class="theme-button">Open</button><button id="save" class="primary-action">Save</button><button id="save-as" class="theme-button">Save As</button></div></header><main class="workspace"><aside class="sidebar"><h2>Project</h2><button class="side-button active" data-view="writing">Writing</button><button class="side-button" data-view="manuscript">Manuscript</button><button class="side-button" data-view="characters">Characters</button><button class="side-button" data-view="worldbuilding">Worldbuilding</button><button class="side-button" data-view="timeline">Timeline</button><button class="side-button" data-view="research">Research</button><button class="side-button" data-view="statistics">Statistics</button><div class="sidebar-spacer"></div><button class="side-button" data-view="settings">Settings</button></aside><section class="editor-area"><div class="toolbar"><button data-command="bold"><b>B</b></button><button data-command="italic"><i>I</i></button><button data-command="underline"><u>U</u></button><span class="toolbar-separator"></span><select id="font">${fonts.map(f=>`<option value="${f}" style="font-family:'${f}'">${f}</option>`).join('')}</select><select id="size">${sizes.map(s=>`<option value="${s}">${s}</option>`).join('')}</select><button id="text-color">A</button><button id="highlight-color">▰</button><span class="toolbar-separator"></span><button data-command="justifyLeft">Left</button><button data-command="justifyCenter">Center</button><button data-command="justifyRight">Right</button></div><article id="editor" class="page" contenteditable="true" spellcheck="true"></article><footer class="statusbar"><span id="save-status">Ready</span><span id="stats">0 words · 0 characters</span></footer></section></main>`;bindEditor();loadEditorContent();}
 function loadEditorContent(){const d=getCurrentDocument(),e=document.querySelector('#editor');if(activeChapter){const c=getChapters().find(x=>x.id===activeChapter);e.innerHTML=`<div class="chapter-heading" contenteditable="false">${esc(c?.title||'Chapter')}</div><div class="chapter-body">${c?.content||''}</div>`;}else e.innerHTML=d.content||'';updateStats(e.innerText);}
 async function openDocument(doc){setCurrentDocument(doc);clearCurrentPath();activeChapter=null;isDirty=false;renderEditor();}
 function updateStats(t){const s=document.querySelector('#stats');if(s)s.textContent=`${countWords(t)} words · ${countCharacters(t)} characters`;}
 function dirty(){isDirty=true;const s=document.querySelector('#save-status');if(s)s.textContent='Unsaved changes';}
 function syncEditor(){const e=document.querySelector('#editor'),d=getCurrentDocument();if(!e||!d)return;if(activeChapter){const c=getChapters().find(x=>x.id===activeChapter);if(c){const body=e.querySelector('.chapter-body');c.content=body?body.innerHTML:e.innerHTML;}}else updateDocumentContent(e.innerHTML);}
 function getChapters(){const d=getCurrentDocument();d.metadata=d.metadata||{};d.metadata.chapters=d.metadata.chapters||[{id:crypto.randomUUID(),title:'Chapter 1',content:''}];d.metadata.chapters.forEach(c=>{if(!('content'in c))c.content='';});return d.metadata.chapters;}
 function renderChapters(){const el=document.querySelector('#chapters');if(!el)return;el.innerHTML=getChapters().map(c=>`<div class="chapter-row" draggable="true" data-id="${c.id}"><span class="drag">☷</span><button class="chapter-open theme-button" data-open-chapter="${c.id}">${esc(c.title)}</button><input value="${esc(c.title)}" data-chapter-title="${c.id}"><button class="theme-button" data-delete-chapter="${c.id}">Delete</button></div>`).join('');el.querySelectorAll('.chapter-open').forEach(b=>b.onclick=()=>openChapter(b.dataset.openChapter));el.querySelectorAll('[data-chapter-title]').forEach(x=>x.oninput=()=>{const c=getChapters().find(c=>c.id===x.dataset.chapterTitle);if(c){c.title=x.value;dirty();}});el.querySelectorAll('[data-delete-chapter]').forEach(x=>x.onclick=()=>{const a=getChapters();if(a.length>1){const i=a.findIndex(c=>c.id===x.dataset.deleteChapter);if(activeChapter===a[i].id)activeChapter=null;a.splice(i,1);dirty();renderChapters();}});let dragged=null;el.querySelectorAll('.chapter-row').forEach(row=>{row.ondragstart=()=>dragged=row.dataset.id;row.ondragover=e=>e.preventDefault();row.ondrop=()=>{const a=getChapters(),from=a.findIndex(c=>c.id===dragged),to=a.findIndex(c=>c.id===row.dataset.id);if(from<0||to<0)return;const [item]=a.splice(from,1);a.splice(to,0,item);dirty();renderChapters();};});}
 function addChapter(){const a=getChapters();const c={id:crypto.randomUUID(),title:`Chapter ${a.length+1}`,content:''};a.push(c);dirty();renderChapters();openChapter(c.id);}
 function openChapter(id){syncEditor();activeChapter=id;const c=getChapters().find(x=>x.id===id);if(c){document.querySelector('#title').value=c.title;loadEditorContent();document.querySelector('.toolbar').hidden=false;document.querySelector('#editor').hidden=false;document.querySelector('.statusbar').hidden=false;document.querySelector('#workspace-panel')?.remove();document.querySelectorAll('.side-button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='writing'));}}
 function showView(view,button){syncEditor();closePalette();document.querySelectorAll('.side-button[data-view]').forEach(x=>x.classList.toggle('active',x===button));const e=document.querySelector('#editor'),t=document.querySelector('.toolbar'),s=document.querySelector('.statusbar');if(view==='writing'){t.hidden=false;e.hidden=false;s.hidden=false;document.querySelector('#workspace-panel')?.remove();loadEditorContent();return;}t.hidden=true;e.hidden=true;s.hidden=true;let p=document.querySelector('#workspace-panel');if(!p){p=document.createElement('section');p.id='workspace-panel';p.className='page workspace-panel';document.querySelector('.editor-area').insertBefore(p,s);}p.hidden=false;
  if(view==='manuscript'){p.innerHTML=`<div class="explorer-header"><div><h1>Manuscript</h1><p>Open a chapter to write inside its own studio.</p></div><button id="add-chapter" class="primary-action">+ Chapter</button></div><div id="chapters" class="explorer-list"></div>`;renderChapters();document.querySelector('#add-chapter').onclick=addChapter;return;}
  if(view==='timeline'){renderTimeline(p);return;}
  if(view==='characters'){renderRecords(p,'characters','Character','characters');return;}
  if(view==='worldbuilding'){renderRecords(p,'locations','Location','locations');return;}
  if(view==='research'){renderRecords(p,'research','Research Item','research');return;}
  if(view==='statistics'){p.innerHTML=`<div class="explorer-header"><div><h1>Statistics</h1><p>Your manuscript at a glance.</p></div></div><div class="stats-grid"><div class="stat-card"><strong>${countWords(getCurrentDocument().content||'')}</strong><span>Total words</span></div><div class="stat-card"><strong>${getChapters().length}</strong><span>Chapters</span></div><div class="stat-card"><strong>${getTimeline().length}</strong><span>Timeline events</span></div></div>`;return;}
  p.innerHTML=`<div class="explorer-header"><div><h1>Settings</h1><p>ScriptSmith preferences.</p></div></div><div class="feature-placeholder">Settings will expand here as the studio grows.</div>`;
 }
 function getRecords(key){const d=getCurrentDocument();d.metadata=d.metadata||{};d.metadata[key]=d.metadata[key]||[];return d.metadata[key];}
 function renderRecords(p,key,label,kind){const records=getRecords(key);p.innerHTML=`<div class="explorer-header"><div><h1>${label}s</h1><p>Keep ${label.toLowerCase()} information with this story.</p></div><button id="add-record" class="primary-action">+ Add ${label}</button></div><div id="record-list" class="explorer-list">${records.length?records.map(r=>`<button class="record-row theme-card" data-record="${r.id}"><strong>${esc(r.name||'Untitled '+label)}</strong><span>${esc(r.summary||'Click to open profile')}</span></button>`).join(''):'<div class="feature-placeholder">Nothing here yet. Add your first one.</div>'}</div>`;p.querySelector('#add-record').onclick=()=>{const r={id:crypto.randomUUID(),name:`New ${label}`,summary:'',notes:''};records.push(r);dirty();renderRecords(p,key,label,kind);openRecord(p,key,label,r.id);};p.querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>openRecord(p,key,label,b.dataset.record));}
 function openRecord(p,key,label,id){const r=getRecords(key).find(x=>x.id===id);if(!r)return;p.innerHTML=`<div class="explorer-header"><div><button id="records-back" class="theme-button">‹ Back</button><h1>${esc(r.name)}</h1></div><button id="records-delete" class="theme-button">Delete</button></div><div class="record-form"><label>Name<input id="record-name" value="${esc(r.name)}"></label><label>Summary<textarea id="record-summary">${esc(r.summary||'')}</textarea></label><label>Notes<textarea id="record-notes">${esc(r.notes||'')}</textarea></label></div>`;p.querySelector('#records-back').onclick=()=>renderRecords(p,key,label,key);p.querySelector('#records-delete').onclick=()=>{const a=getRecords(key),i=a.findIndex(x=>x.id===id);if(i>=0)a.splice(i,1);dirty();renderRecords(p,key,label,key);};p.querySelector('#record-name').oninput=e=>{r.name=e.target.value;dirty();};p.querySelector('#record-summary').oninput=e=>{r.summary=e.target.value;dirty();};p.querySelector('#record-notes').oninput=e=>{r.notes=e.target.value;dirty();};}
 function getTimeline(){const d=getCurrentDocument();d.metadata=d.metadata||{};d.metadata.timeline=d.metadata.timeline||[];return d.metadata.timeline;}
 function renderTimeline(p){const all=getTimeline(),dated=all.filter(x=>x.date).sort((a,b)=>a.date.localeCompare(b.date)),undated=all.filter(x=>!x.date),items=[...dated,...undated];p.innerHTML=`<div class="explorer-header"><div><h1>Timeline</h1><p>Chronological events run down the line. Click an event to open its details.</p></div><button id="add-event" class="primary-action">+ Event</button></div><div class="vertical-timeline" id="timeline-list">${items.map(x=>`<div class="timeline-event ${x.date?'dated':'undated'}" draggable="${!x.date}" data-event="${x.id}"><div class="timeline-dot"></div><button class="timeline-card theme-card" data-open-event="${x.id}"><strong>${esc(x.title||'New event')}</strong><span>${x.date?esc(x.date):'Undated'}</span></button></div>`).join('')}</div>`;p.querySelector('#add-event').onclick=()=>{all.push({id:crypto.randomUUID(),title:'New event',date:'',summary:'',notes:''});dirty();renderTimeline(p);};p.querySelectorAll('[data-open-event]').forEach(b=>b.onclick=()=>openTimelineEvent(p,b.dataset.openEvent));let dragged=null;p.querySelectorAll('.timeline-event.undated').forEach(r=>{r.ondragstart=()=>dragged=r.dataset.event;r.ondragover=e=>e.preventDefault();r.ondrop=()=>{const und=all.filter(e=>!e.date),from=und.findIndex(e=>e.id===dragged),to=und.findIndex(e=>e.id===r.dataset.event);if(from<0||to<0)return;const [x]=und.splice(from,1);und.splice(to,0,x);const datedNow=all.filter(e=>e.date);all.splice(0,all.length,...datedNow,...und);dirty();renderTimeline(p);};});}
 function openTimelineEvent(p,id){const e=getTimeline().find(x=>x.id===id);if(!e)return;p.innerHTML=`<div class="explorer-header"><div><button id="timeline-back" class="theme-button">‹ Timeline</button><h1>${esc(e.title||'Event')}</h1></div><button id="timeline-delete" class="theme-button">Delete</button></div><div class="record-form"><label>Event Name<input id="event-title" value="${esc(e.title||'')}"></label><label>Date<input id="event-date" type="date" value="${esc(e.date||'')}"></label><label>Summary<textarea id="event-summary">${esc(e.summary||'')}</textarea></label><label>Details<textarea id="event-notes">${esc(e.notes||'')}</textarea></label></div>`;p.querySelector('#timeline-back').onclick=()=>renderTimeline(p);p.querySelector('#timeline-delete').onclick=()=>{const a=getTimeline(),i=a.findIndex(x=>x.id===id);if(i>=0)a.splice(i,1);dirty();renderTimeline(p);};p.querySelector('#event-title').oninput=x=>{e.title=x.target.value;dirty();};p.querySelector('#event-date').onchange=x=>{e.date=x.target.value;dirty();};p.querySelector('#event-summary').oninput=x=>{e.summary=x.target.value;dirty();};p.querySelector('#event-notes').oninput=x=>{e.notes=x.target.value;dirty();};}
 async function save(as=false){syncEditor();try{if(await saveProject(getCurrentDocument(),as)){isDirty=false;document.querySelector('#save-status').textContent='Saved';await clearAutosave();await refreshLibrary();}}catch(e){document.querySelector('#save-status').textContent='Save failed';}}
 async function autosave(){if(!isDirty||autosaveBusy)return;autosaveBusy=true;syncEditor();try{await saveAutosave(getCurrentDocument());}finally{autosaveBusy=false;}}
 function closePalette(){document.querySelectorAll('.color-palette').forEach(x=>x.remove());}
 function colorPalette(kind){closePalette();const box=document.createElement('div');box.className='color-palette';const custom=JSON.parse(localStorage.getItem('scriptsmith-custom-colors')||'[]');[...new Set([...custom,...palette])].forEach(c=>{const b=document.createElement('button');b.className='color-swatch';b.style.background=c;b.title=c;b.onclick=e=>{e.stopPropagation();applyColor(kind,c);closePalette();};box.appendChild(b);});const picker=document.createElement('input');picker.type='color';picker.title='Choose custom color';picker.style.gridColumn='1/-1';picker.onchange=e=>{const c=e.target.value,arr=JSON.parse(localStorage.getItem('scriptsmith-custom-colors')||'[]');if(!arr.includes(c))arr.unshift(c);localStorage.setItem('scriptsmith-custom-colors',JSON.stringify(arr.slice(0,16)));applyColor(kind,c);closePalette();};box.appendChild(picker);document.body.appendChild(box);const anchor=document.querySelector(kind==='text'?'#text-color':'#highlight-color');const r=anchor.getBoundingClientRect();box.style.left=`${r.left}px`;box.style.top=`${r.bottom+4}px`;box.onclick=e=>e.stopPropagation();}
 function applyColor(kind,c){const e=document.querySelector('#editor');e.focus();document.execCommand(kind==='text'?'foreColor':'hiliteColor',false,c);dirty();}
 function bindEditor(){const e=document.querySelector('#editor'),title=document.querySelector('#title');e.addEventListener('input',()=>{syncEditor();updateStats(e.innerText);dirty();});title.oninput=()=>{updateDocumentTitle(title.value);if(activeChapter){const c=getChapters().find(x=>x.id===activeChapter);if(c)c.title=title.value;const h=e.querySelector('.chapter-heading');if(h)h.textContent=title.value;}dirty();};document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{e.focus();document.execCommand(b.dataset.command,false);dirty();});document.querySelector('#font').onchange=x=>{e.focus();document.execCommand('fontName',false,x.target.value);dirty();};document.querySelector('#size').onchange=x=>{e.focus();document.execCommand('fontSize',false,'7');e.querySelectorAll('font[size="7"]').forEach(n=>{n.removeAttribute('size');n.style.fontSize=`${x.target.value}pt`;});dirty();};document.querySelector('#text-color').onclick=e2=>{e2.stopPropagation();colorPalette('text');};document.querySelector('#highlight-color').onclick=e2=>{e2.stopPropagation();colorPalette('highlight');};document.querySelectorAll('.side-button[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view,b));document.querySelector('#save').onclick=()=>save(false);document.querySelector('#save-as').onclick=()=>save(true);document.querySelector('#new').onclick=()=>newDocument('document');document.querySelector('#open').onclick=async()=>{const d=await openProject();if(d)await openDocument(d);};document.querySelector('#back-home').onclick=async()=>{syncEditor();if(isDirty&&!confirm('You have unsaved changes. Return to Library anyway?'))return;showHome();};}
 function newDocument(type){const d=createDocument();d.type=type;d.title=({novel:'Untitled Novel',novella:'Untitled Novella','short-story':'Untitled Short Story',screenplay:'Untitled Screenplay',poetry:'Untitled Poem'})[type]||'Untitled Document';setCurrentDocument(d);clearCurrentPath();activeChapter=null;isDirty=false;renderEditor();}
 document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>showCollection(b.dataset.template));document.querySelector('#home-open').onclick=async()=>{const d=await openProject();if(d)await openDocument(d);};document.querySelector('#universal-characters').onclick=()=>showUniversal('characters');document.querySelector('#universal-world').onclick=()=>showUniversal('locations');document.querySelector('#home-settings').onclick=()=>alert('Settings will be available in a future sprint.');document.addEventListener('click',()=>closePalette());setInterval(autosave,AUTOSAVE_INTERVAL);refreshLibrary();
 function showUniversal(type){const data=universal();const label=type==='characters'?'Universal Characters':'Universal World';document.querySelector('#home').hidden=true;document.querySelector('#collection-shell').hidden=false;const shell=document.querySelector('#collection-shell');shell.innerHTML=`<header class="topbar"><div class="brand"><button id="universal-home" class="home-button theme-button">‹ Library</button><span class="brand-mark">S</span><div><strong>ScriptSmith</strong><small>${label}</small></div></div><div></div><div class="top-actions"><button id="universal-add" class="primary-action">+ Add ${type==='characters'?'Character':'Location'}</button></div></header><main class="collection-page"><div class="collection-heading"><h1>${label}</h1><p>Shared across all of your stories.</p></div><div id="universal-list" class="library-grid">${data[type].length?data[type].map(r=>`<button class="record-row theme-card" data-universal="${r.id}"><strong>${esc(r.name)}</strong><span>${esc(r.summary||'')}</span></button>`).join(''):'<div class="library-empty">Nothing here yet.</div>'}</div></main>`;document.querySelector('#universal-home').onclick=showHome;document.querySelector('#universal-add').onclick=()=>{data[type].push({id:crypto.randomUUID(),name:type==='characters'?'New Character':'New Location',summary:'',notes:''});saveUniversal(data);showUniversal(type);};document.querySelectorAll('[data-universal]').forEach(b=>b.onclick=()=>editUniversal(type,b.dataset.universal));}
 function editUniversal(type,id){const data=universal(),r=data[type].find(x=>x.id===id);if(!r)return;const shell=document.querySelector('#collection-shell');shell.innerHTML=`<header class="topbar"><div class="brand"><button id="u-back" class="home-button theme-button">‹ Back</button><span class="brand-mark">S</span><div><strong>ScriptSmith</strong><small>Universal Library</small></div></div></header><main class="collection-page"><div class="record-form"><label>Name<input id="u-name" value="${esc(r.name)}"></label><label>Summary<textarea id="u-summary">${esc(r.summary||'')}</textarea></label><label>Notes<textarea id="u-notes">${esc(r.notes||'')}</textarea></label><button id="u-save" class="primary-action">Save</button></div></main>`;document.querySelector('#u-back').onclick=()=>showUniversal(type);document.querySelector('#u-save').onclick=()=>{r.name=document.querySelector('#u-name').value;r.summary=document.querySelector('#u-summary').value;r.notes=document.querySelector('#u-notes').value;saveUniversal(data);showUniversal(type);};}
 async function checkRecovery(){try{if(await hasAutosave()){const d=await loadAutosave();if(d&&confirm(`Restore recovered copy of “${d.title||'Untitled Document'}”?`)){setCurrentDocument(d);renderEditor();isDirty=true;}else await clearAutosave();}}catch(_) {}}
 checkRecovery();function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}function date(v){try{return new Date(v).toLocaleDateString([], {month:'short',day:'numeric',year:'numeric'});}catch(_){return '';}}
}
