import { createDocument, getCurrentDocument, setCurrentDocument, updateDocumentContent, updateDocumentTitle } from './document.js';
import { saveProject, openProject, clearCurrentPath, saveAutosave, clearAutosave, hasAutosave, loadAutosave, listLibraryDocuments, loadLibraryDocument } from './filesystem.js';
import { countWords, countCharacters } from './statistics.js';

const AUTOSAVE_INTERVAL=10000;
const fonts=['Georgia','Times New Roman','Arial','Calibri','Garamond','Verdana','Tahoma','Trebuchet MS','Courier New','Lucida Console','Palatino Linotype','Book Antiqua','Cambria','Century Gothic','Consolas','Franklin Gothic Medium','Impact','Lucida Sans Unicode','Segoe UI','Gill Sans','Helvetica','Arial Black'];
const sizes=Array.from({length:56},(_,i)=>i+9);
const templates=[['Blank Document','document'],['Novel','novel'],['Novella','novella'],['Short Story','short-story'],['Screenplay','screenplay'],['Poetry','poetry']];
const palette=['#000000','#434343','#666666','#999999','#b7b7b7','#cccccc','#d9d9d9','#efefef','#f4cccc','#ea9999','#e06666','#cc0000','#990000','#660000','#e6b8af','#fce5cd','#f9cb9c','#f6b26b','#e69138','#b45f06','#783f04','#fff2cc','#ffe599','#ffd966','#f1c232','#bf9000','#7f6000','#d9ead3','#b6d7a8','#93c47d','#6aa84f','#38761d','#274e13','#d0e0e3','#a2c4c9','#76a5af','#45818e','#134f5c','#0b5394','#c9daf8','#a4c2f4','#6d9eeb','#3c78d8','#1155cc','#1c4587'];

export function initApp(){
 const app=document.querySelector('#app');setCurrentDocument(createDocument());clearCurrentPath();let isDirty=false,autosaveBusy=false,activeChapter=null;
 app.innerHTML=`<div class="home" id="home"><header class="home-header"><div class="brand"><span class="brand-mark">S</span><div><strong>ScriptSmith</strong><small>Writer's Studio</small></div></div><button id="home-settings">Settings</button></header><main class="home-content"><section class="welcome"><h1>What will you write?</h1><p>Start something new or return to a project.</p><div class="template-grid" id="templates">${templates.map(([n,t])=>`<button class="template-card" data-template="${t}"><strong>${n}</strong><span>Start a new ${n.toLowerCase()}</span></button>`).join('')}</div></section><section class="library-section"><div class="section-heading"><div><h2>Your Library</h2><p>Your ScriptSmith projects stay available inside the app.</p></div><button id="home-open">Open from computer</button></div><div id="library" class="library-grid"><div class="library-empty">Loading your library…</div></div></section></main></div><div id="editor-shell" hidden></div>`;
 async function refreshLibrary(){const el=document.querySelector('#library'),docs=await listLibraryDocuments();if(!docs.length){el.innerHTML='<div class="library-empty">No saved projects yet. Start a document above and save it.</div>';return;}el.innerHTML=docs.map(d=>`<button class="project-card" data-library-id="${d.libraryId||d.id}"><span class="project-icon">S</span><span><strong>${esc(d.title||'Untitled Document')}</strong><small>${date(d.libraryUpdatedAt||d.updatedAt)}</small></span></button>`).join('');el.querySelectorAll('.project-card').forEach(c=>c.onclick=async()=>{const d=docs.find(x=>(x.libraryId||x.id)===c.dataset.libraryId);if(d)await openDocument(await loadLibraryDocument(d));});}
 function renderEditor(){document.querySelector('#home').hidden=true;const shell=document.querySelector('#editor-shell');shell.hidden=false;const d=getCurrentDocument();shell.innerHTML=`<header class="topbar"><div class="brand"><button id="back-home" class="home-button">‹ Library</button><span class="brand-mark">S</span><div><strong>ScriptSmith</strong><small>Writer's Studio</small></div></div><div class="document-title"><input id="title" value="${esc(d.title)}" aria-label="Document title"></div><div class="top-actions"><button id="new">New</button><button id="open">Open</button><button id="save">Save</button><button id="save-as">Save As</button></div></header><main class="workspace"><aside class="sidebar"><h2>Project</h2><button class="side-button active" data-view="writing">Writing</button><button class="side-button" data-view="manuscript">Manuscript</button><button class="side-button" data-view="characters">Characters</button><button class="side-button" data-view="worldbuilding">Worldbuilding</button><button class="side-button" data-view="timeline">Timeline</button><button class="side-button" data-view="research">Research</button><button class="side-button" data-view="statistics">Statistics</button><div class="sidebar-spacer"></div><button class="side-button" data-view="settings">Settings</button></aside><section class="editor-area"><div class="toolbar"><button data-command="bold"><b>B</b></button><button data-command="italic"><i>I</i></button><button data-command="underline"><u>U</u></button><span class="toolbar-separator"></span><select id="font">${fonts.map(f=>`<option value="${f}" style="font-family:'${f}'">${f}</option>`).join('')}</select><select id="size">${sizes.map(s=>`<option value="${s}">${s}</option>`).join('')}</select><button id="text-color">A</button><button id="highlight-color">▰</button><span class="toolbar-separator"></span><button data-command="justifyLeft">Left</button><button data-command="justifyCenter">Center</button><button data-command="justifyRight">Right</button></div><article id="editor" class="page" contenteditable="true" spellcheck="true"></article><footer class="statusbar"><span id="save-status">Ready</span><span id="stats">0 words · 0 characters</span></footer></section></main>`;bindEditor();loadEditorContent();}
 function loadEditorContent(){const d=getCurrentDocument(),e=document.querySelector('#editor');e.innerHTML=activeChapter?(getChapters().find(c=>c.id===activeChapter)?.content||''):d.content||'';updateStats(e.innerText);}
 async function openDocument(doc){setCurrentDocument(doc);clearCurrentPath();activeChapter=null;isDirty=false;renderEditor();}
 function updateStats(t){const s=document.querySelector('#stats');if(s)s.textContent=`${countWords(t)} words · ${countCharacters(t)} characters`;}
 function dirty(){isDirty=true;const s=document.querySelector('#save-status');if(s)s.textContent='Unsaved changes';}
 function syncEditor(){const e=document.querySelector('#editor'),d=getCurrentDocument();if(!e||!d)return;if(activeChapter){const c=getChapters().find(x=>x.id===activeChapter);if(c)c.content=e.innerHTML;}else updateDocumentContent(e.innerHTML);}
 function getChapters(){const d=getCurrentDocument();d.metadata=d.metadata||{};d.metadata.chapters=d.metadata.chapters||[{id:crypto.randomUUID(),title:'Chapter 1',content:''}];d.metadata.chapters.forEach(c=>{if(!('content'in c))c.content='';});return d.metadata.chapters;}
 function renderChapters(){const el=document.querySelector('#chapters');if(!el)return;el.innerHTML=getChapters().map((c,i)=>`<div class="chapter-row" draggable="true" data-id="${c.id}"><span class="drag">☷</span><button class="chapter-open" data-open-chapter="${c.id}">${esc(c.title)}</button><input value="${esc(c.title)}" data-chapter-title="${c.id}"><button data-delete-chapter="${c.id}">Delete</button></div>`).join('');el.querySelectorAll('.chapter-open').forEach(b=>b.onclick=()=>openChapter(b.dataset.openChapter));el.querySelectorAll('[data-chapter-title]').forEach(x=>x.oninput=()=>{const c=getChapters().find(c=>c.id===x.dataset.chapterTitle);if(c){c.title=x.value;dirty();const b=document.querySelector(`[data-open-chapter="${c.id}"]`);if(b)b.textContent=x.value;}});el.querySelectorAll('[data-delete-chapter]').forEach(x=>x.onclick=()=>{const a=getChapters();if(a.length>1){const i=a.findIndex(c=>c.id===x.dataset.deleteChapter);if(activeChapter===a[i].id)activeChapter=null;a.splice(i,1);dirty();renderChapters();}});let dragged=null;el.querySelectorAll('.chapter-row').forEach(row=>{row.ondragstart=()=>dragged=row.dataset.id;row.ondragover=e=>e.preventDefault();row.ondrop=()=>{const a=getChapters(),from=a.findIndex(c=>c.id===dragged),to=a.findIndex(c=>c.id===row.dataset.id);if(from<0||to<0)return;const [item]=a.splice(from,1);a.splice(to,0,item);dirty();renderChapters();};});}
 function addChapter(){const a=getChapters();const n=a.length+1;a.push({id:crypto.randomUUID(),title:`Chapter ${n}`,content:''});dirty();renderChapters();openChapter(a[a.length-1].id);}
 function openChapter(id){syncEditor();activeChapter=id;const c=getChapters().find(x=>x.id===id);if(c){document.querySelector('#title').value=c.title;document.querySelector('#editor').innerHTML=c.content||'';document.querySelector('.toolbar').hidden=false;document.querySelector('#editor').hidden=false;document.querySelector('.statusbar').hidden=false;document.querySelector('#workspace-panel')?.remove();document.querySelectorAll('.side-button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='writing'));updateStats(document.querySelector('#editor').innerText);}}
 function showView(view,button){syncEditor();document.querySelectorAll('.side-button[data-view]').forEach(x=>x.classList.toggle('active',x===button));const e=document.querySelector('#editor'),t=document.querySelector('.toolbar'),s=document.querySelector('.statusbar');if(view==='writing'){t.hidden=false;e.hidden=false;s.hidden=false;document.querySelector('#workspace-panel')?.remove();loadEditorContent();return;}t.hidden=true;e.hidden=true;s.hidden=true;let p=document.querySelector('#workspace-panel');if(!p){p=document.createElement('section');p.id='workspace-panel';p.className='page workspace-panel';document.querySelector('.editor-area').insertBefore(p,s);}p.hidden=false;
  if(view==='manuscript'){p.innerHTML=`<div class="explorer-header"><div><h1>Manuscript</h1><p>Each chapter opens into its own writing studio.</p></div><button id="add-chapter" class="primary-action">+ Chapter</button></div><div id="chapters" class="explorer-list"></div>`;renderChapters();document.querySelector('#add-chapter').onclick=addChapter;return;}
  if(view==='timeline'){renderTimeline(p);return;}
  const labels={characters:['Characters','Build and manage characters for this story.'],worldbuilding:['World','Build the setting and locations for this story.'],research:['Research','Keep notes and references for this project.'],statistics:['Statistics','View writing statistics here.'],settings:['Settings','ScriptSmith settings will live here.']};const [h,m]=labels[view]||labels.settings;p.innerHTML=`<div class="explorer-header"><div><h1>${h}</h1><p>${m}</p></div><button class="primary-action">+ Add ${h==='World'?'Location':h==='Characters'?'Character':'Item'}</button></div><div class="feature-placeholder">This workspace is ready for the next phase.</div>`;
 }
 function getTimeline(){const d=getCurrentDocument();d.metadata=d.metadata||{};d.metadata.timeline=d.metadata.timeline||[];return d.metadata.timeline;}
 function renderTimeline(p){const all=getTimeline(),dated=all.filter(x=>x.date).sort((a,b)=>a.date.localeCompare(b.date)),undated=all.filter(x=>!x.date),items=[...dated,...undated];p.innerHTML=`<div class="explorer-header"><div><h1>Timeline</h1><p>Dated events sort automatically. Undated events can be dragged into your preferred order.</p></div><button id="add-event" class="primary-action">+ Event</button></div><div id="timeline-list" class="timeline-list">${items.map(x=>`<div class="timeline-row" draggable="${!x.date}" data-event="${x.id}"><span class="drag">${x.date?'◆':'☷'}</span><input class="date" type="date" value="${esc(x.date||'')}" data-date="${x.id}"><input value="${esc(x.title||'New event')}" data-event-title="${x.id}"><button data-delete-event="${x.id}">Delete</button></div>`).join('')}</div>`;p.querySelector('#add-event').onclick=()=>{all.push({id:crypto.randomUUID(),title:'New event',date:''});dirty();renderTimeline(p);};p.querySelectorAll('[data-date]').forEach(i=>i.onchange=()=>{const x=all.find(e=>e.id===i.dataset.date);if(x){x.date=i.value;dirty();renderTimeline(p);}});p.querySelectorAll('[data-event-title]').forEach(i=>i.oninput=()=>{const x=all.find(e=>e.id===i.dataset.eventTitle);if(x){x.title=i.value;dirty();}});p.querySelectorAll('[data-delete-event]').forEach(b=>b.onclick=()=>{const i=all.findIndex(e=>e.id===b.dataset.deleteEvent);if(i>=0){all.splice(i,1);dirty();renderTimeline(p);}});let dragged=null;p.querySelectorAll('.timeline-row[draggable="true"]').forEach(r=>{r.ondragstart=()=>dragged=r.dataset.event;r.ondragover=e=>e.preventDefault();r.ondrop=()=>{const und=all.filter(e=>!e.date),from=und.findIndex(e=>e.id===dragged),to=und.findIndex(e=>e.id===r.dataset.event);if(from<0||to<0)return;const [x]=und.splice(from,1);und.splice(to,0,x);const dated=all.filter(e=>e.date);all.splice(0,all.length,...dated,...und);dirty();renderTimeline(p);};});}
 async function save(as=false){syncEditor();try{if(await saveProject(getCurrentDocument(),as)){isDirty=false;document.querySelector('#save-status').textContent='Saved';await clearAutosave();await refreshLibrary();}}catch(e){document.querySelector('#save-status').textContent='Save failed';}}
 async function autosave(){if(!isDirty||autosaveBusy)return;autosaveBusy=true;syncEditor();try{await saveAutosave(getCurrentDocument());}finally{autosaveBusy=false;}}
 function colorPalette(kind){document.querySelectorAll('.color-palette').forEach(x=>x.remove());const box=document.createElement('div');box.className='color-palette';const custom=JSON.parse(localStorage.getItem('scriptsmith-custom-colors')||'[]');[...new Set([...custom,...palette])].forEach(c=>{const b=document.createElement('button');b.className='color-swatch';b.style.background=c;b.title=c;b.onclick=()=>{applyColor(kind,c);box.remove();};box.appendChild(b);});const picker=document.createElement('input');picker.type='color';picker.title='Choose custom color';picker.style.width='100%';picker.style.height='28px';picker.style.gridColumn='1/-1';picker.onchange=()=>{const c=picker.value;const arr=JSON.parse(localStorage.getItem('scriptsmith-custom-colors')||'[]');if(!arr.includes(c))arr.unshift(c);localStorage.setItem('scriptsmith-custom-colors',JSON.stringify(arr.slice(0,16)));applyColor(kind,c);box.remove();};box.appendChild(picker);document.body.appendChild(box);const anchor=document.querySelector(kind==='text'?'#text-color':'#highlight-color');const r=anchor.getBoundingClientRect();box.style.left=`${r.left}px`;box.style.top=`${r.bottom+4}px`;}
 function applyColor(kind,c){const e=document.querySelector('#editor');e.focus();document.execCommand(kind==='text'?'foreColor':'hiliteColor',false,c);dirty();}
 function bindEditor(){const e=document.querySelector('#editor'),title=document.querySelector('#title');e.addEventListener('input',()=>{syncEditor();updateStats(e.innerText);dirty();});title.oninput=()=>{updateDocumentTitle(title.value);if(activeChapter){const c=getChapters().find(x=>x.id===activeChapter);if(c)c.title=title.value;}dirty();};document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{e.focus();document.execCommand(b.dataset.command,false);dirty();});document.querySelector('#font').onchange=x=>{e.focus();document.execCommand('fontName',false,x.target.value);dirty();};document.querySelector('#size').onchange=x=>{e.focus();document.execCommand('fontSize',false,'7');e.querySelectorAll('font[size="7"]').forEach(n=>{n.removeAttribute('size');n.style.fontSize=`${x.target.value}pt`;});dirty();};document.querySelector('#text-color').onclick=()=>colorPalette('text');document.querySelector('#highlight-color').onclick=()=>colorPalette('highlight');document.querySelectorAll('.side-button[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view,b));document.querySelector('#save').onclick=()=>save(false);document.querySelector('#save-as').onclick=()=>save(true);document.querySelector('#new').onclick=()=>newDocument('document');document.querySelector('#open').onclick=async()=>{const d=await openProject();if(d)await openDocument(d);};document.querySelector('#back-home').onclick=async()=>{syncEditor();if(isDirty&&!confirm('You have unsaved changes. Return to Library anyway?'))return;document.querySelector('#editor-shell').hidden=true;document.querySelector('#home').hidden=false;await refreshLibrary();};}
 function newDocument(type){const d=createDocument();d.type=type;d.title=({novel:'Untitled Novel',novella:'Untitled Novella','short-story':'Untitled Short Story',screenplay:'Untitled Screenplay',poetry:'Untitled Poem'})[type]||'Untitled Document';setCurrentDocument(d);clearCurrentPath();activeChapter=null;isDirty=false;renderEditor();}
 document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>newDocument(b.dataset.template));document.querySelector('#home-open').onclick=async()=>{const d=await openProject();if(d)await openDocument(d);};document.querySelector('#home-settings').onclick=()=>alert('Settings will be available in a future sprint.');setInterval(autosave,AUTOSAVE_INTERVAL);refreshLibrary();
 async function checkRecovery(){try{if(await hasAutosave()){const d=await loadAutosave();if(d&&confirm(`Restore recovered copy of “${d.title||'Untitled Document'}”?`)){setCurrentDocument(d);renderEditor();isDirty=true;}else await clearAutosave();}}catch(_) {}}
 checkRecovery();function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}function date(v){try{return new Date(v).toLocaleDateString([], {month:'short',day:'numeric',year:'numeric'});}catch(_){return '';}}
}
