const CURRENT_DOCUMENT_VERSION = 3;
let currentDocument = null;
const DEFAULT_MANUSCRIPT_PREFERENCES = { fontFamily:'Georgia', fontSize:12, lineSpacing:1, header:'', footer:'', pageNumbers:false };
export function createDocument(){return {id:crypto.randomUUID(),version:CURRENT_DOCUMENT_VERSION,title:'Untitled Document',type:'document',content:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),metadata:{author:'',notes:'',chapters:[{id:crypto.randomUUID(),title:'Chapter 1',content:''}],characters:[],locations:[],research:[],timeline:[],notes:[],books:[],prologue:{enabled:false,title:'Prologue',content:''},epilogue:{enabled:false,title:'Epilogue',content:''},tableOfContents:{mode:'automatic',entries:[]},sessions:[],manuscriptPreferences:{...DEFAULT_MANUSCRIPT_PREFERENCES}}}};
export function migrateDocument(document){if(!document)return document;const d=structuredClone(document);d.version=Number(d.version||1);d.metadata=d.metadata||{};d.metadata.chapters=Array.isArray(d.metadata.chapters)?d.metadata.chapters:[{id:crypto.randomUUID(),title:'Chapter 1',content:''}];d.metadata.chapters.forEach(c=>{c.id=c.id||crypto.randomUUID();c.title=c.title||'Chapter';if(!('content'in c))c.content=''});for(const key of ['characters','locations','research','timeline','notes','books'])if(!Array.isArray(d.metadata[key]))d.metadata[key]=[];const old=d.metadata.manuscriptPreferences||{};d.metadata.manuscriptPreferences={...DEFAULT_MANUSCRIPT_PREFERENCES,...old,lineSpacing:Number(old.lineSpacing??old.lineHeight??1)||1};delete d.metadata.manuscriptPreferences.lineHeight;d.metadata.prologue={enabled:false,title:'Prologue',content:'',...(d.metadata.prologue||{})};d.metadata.epilogue={enabled:false,title:'Epilogue',content:'',...(d.metadata.epilogue||{})};d.metadata.tableOfContents={mode:'automatic',entries:[],...(d.metadata.tableOfContents||{})};d.metadata.sessions=Array.isArray(d.metadata.sessions)?d.metadata.sessions:[];d.version=CURRENT_DOCUMENT_VERSION;return d}
export function getCurrentDocument(){return currentDocument}
export function setCurrentDocument(document){currentDocument=migrateDocument(document)}
export function updateDocumentContent(content){if(currentDocument){currentDocument.content=content;currentDocument.updatedAt=new Date().toISOString()}}
export function updateDocumentTitle(title){if(currentDocument){currentDocument.title=title||'Untitled Document';currentDocument.updatedAt=new Date().toISOString()}}
export function getDocumentVersion(){return CURRENT_DOCUMENT_VERSION}
