const CURRENT_DOCUMENT_VERSION = 5;
let currentDocument = null;
const DEFAULT_MANUSCRIPT_PREFERENCES = { fontFamily:'Georgia', fontSize:12, lineSpacing:1, header:'', footer:'', pageNumbers:false };
const DEFAULT_MODULES = {writing:true,manuscript:true,characters:true,worldbuilding:true,timeline:true,research:true,notes:true,universalNotes:true,statistics:true,tableOfContents:true,prologue:true,epilogue:true,plotBoard:false,maps:false,familyTrees:false,languages:false,magicSystem:false,species:false,publishingCenter:false,seriesBible:false};
export function createDocument(){return {id:crypto.randomUUID(),version:CURRENT_DOCUMENT_VERSION,title:'Untitled Document',type:'document',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),content:'',metadata:{author:'',notes:'',universalNotes:[],chapters:[],characters:[],locations:[],research:[],timeline:[],notes:[],books:[],prologue:{enabled:false,title:'Prologue',content:''},epilogue:{enabled:false,title:'Epilogue',content:''},tableOfContents:{mode:'automatic',entries:[]},sessions:[],modules:{...DEFAULT_MODULES},manuscriptPreferences:{...DEFAULT_MANUSCRIPT_PREFERENCES}}}};
export function migrateDocument(document){if(!document)return document;const d=structuredClone(document);d.version=CURRENT_DOCUMENT_VERSION;d.metadata=d.metadata||{};for(const key of ['chapters','characters','locations','research','timeline','notes','books'])if(!Array.isArray(d.metadata[key]))d.metadata[key]=[];if(!Array.isArray(d.metadata.universalNotes))d.metadata.universalNotes=[];const old=d.metadata.manuscriptPreferences||{};d.metadata.manuscriptPreferences={...DEFAULT_MANUSCRIPT_PREFERENCES,...old,lineSpacing:Number(old.lineSpacing??old.lineHeight??1)||1};delete d.metadata.manuscriptPreferences.lineHeight;d.metadata.prologue={enabled:false,title:'Prologue',content:'',...(d.metadata.prologue||{})};d.metadata.epilogue={enabled:false,title:'Epilogue',content:'',...(d.metadata.epilogue||{})};d.metadata.tableOfContents={mode:'automatic',entries:[],...(d.metadata.tableOfContents||{})};d.metadata.sessions=Array.isArray(d.metadata.sessions)?d.metadata.sessions:[];d.metadata.modules={...DEFAULT_MODULES,...(d.metadata.modules||{})};return d}
export function getCurrentDocument(){return currentDocument}
export function setCurrentDocument(document){currentDocument=migrateDocument(document)}
export function updateDocumentContent(content){if(currentDocument){currentDocument.content=content;currentDocument.updatedAt=new Date().toISOString()}}
export function updateDocumentTitle(title){if(currentDocument){currentDocument.title=title||'Untitled Document';currentDocument.updatedAt=new Date().toISOString()}}
export function getDocumentVersion(){return CURRENT_DOCUMENT_VERSION}
export function addUniversalNote(title='Universe Note',content=''){if(!currentDocument)return null;const note={id:crypto.randomUUID(),title,content,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};currentDocument.metadata.universalNotes.push(note);return note}
export function updateUniversalNote(id,changes){if(!currentDocument)return;const note=currentDocument.metadata.universalNotes.find(n=>n.id===id);if(note){Object.assign(note,changes,{updatedAt:new Date().toISOString()});}}
export function removeUniversalNote(id){if(currentDocument)currentDocument.metadata.universalNotes=currentDocument.metadata.universalNotes.filter(n=>n.id!==id)}
