import { getCurrentDocument, updateDocumentContent } from './document.js';
import { saveProject, deleteLibraryDocument } from './filesystem.js';
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const toast=message=>{const n=document.createElement('div');n.className='ss-toast';n.textContent=message;document.body.appendChild(n);setTimeout(()=>n.remove(),2200);};
function injectStyle(){if(document.getElementById('ss-enhancement-style'))return;const s=document.createElement('style');s.id='ss-enhancement-style';s.textContent=`#editor.ss-paged{width:100%;max-width:none;min-height:0;height:auto;overflow:visible;background:transparent;box-shadow:none;padding:0;display:flex;flex-direction:column;align-items:center;gap:24px}#editor.ss-paged .ss-page{width:min(816px,calc(100vw - 80px));min-height:1056px;padding:96px 92px;background:#fff;box-shadow:0 3px 14px rgba(40,30,20,.16);box-sizing:border-box;overflow:hidden;flex:0 0 auto}.ss-doc-wrap{display:flex;flex-direction:column;gap:6px}.ss-doc-wrap .project-card{width:100%}.ss-delete-doc{align-self:flex-end}.ss-timeline-actions{display:flex;gap:10px;margin-top:18px}`;document.head.appendChild(s);}
function paginate(e){if(!e||e.dataset.paging)return;e.dataset.paging='1';const blocks=[];[...e.children].forEach(c=>{if(c.classList.contains('ss-page'))blocks.push(...c.childNodes);else blocks.push(c);});if(!blocks.length){const p=document.createElement('div');p.className='ss-page';e.replaceChildren(p);e.dataset.paging='0';return;}e.replaceChildren();let page=document.createElement('div');page.className='ss-page';e.appendChild(page);for(const node of blocks){page.appendChild(node);if(page.scrollHeight>page.clientHeight+2&&page.childNodes.length>1){page.removeChild(node);page=document.createElement('div');page.className='ss-page';e.appendChild(page);page.appendChild(node);}}e.dataset.paging='0';}
function installPagination(){injectStyle();const setup=()=>{const e=document.querySelector('#editor');if(!e||e.dataset.pagingInstalled)return;e.dataset.pagingInstalled='1';e.classList.add('ss-paged');paginate(e);e.addEventListener('input',()=>{clearTimeout(e.__ssPageTimer);e.__ssPageTimer=setTimeout(()=>paginate(e),250);});};new MutationObserver(setup).observe(document.body,{childList:true,subtree:true});setup();}
function sync(){const e=document.querySelector('#editor');if(e)updateDocumentContent(e.innerHTML);}
function saveMenu(){const d=getCurrentDocument();const choices=[['document','Documents'],['novel','Novels'],['novella','Novellas'],['short-story','Short Stories'],['screenplay','Screenplays'],['poetry','Poetry'],['other','Other Writing']];let m=document.getElementById('ss-save-menu');if(!m){m=document.createElement('div');m.id='ss-save-menu';m.className='phase2-modal';document.body.appendChild(m);}m.innerHTML=`<div class="phase2-dialog"><div class="phase2-dialog-head"><h2>Save To</h2><button id="ss-save-close">×</button></div><p>Choose where this document belongs in your ScriptSmith Library.</p><div class="save-options">${choices.map(([type,label])=>`<button class="theme-button" data-ss-save-type="${type}">${label}</button>`).join('')}</div></div>`;m.hidden=false;m.querySelector('#ss-save-close').onclick=()=>m.hidden=true;m.querySelectorAll('[data-ss-save-type]').forEach(b=>b.onclick=async()=>{sync();d.type=b.dataset.ssSaveType;try{await saveProject(d,false);m.hidden=true;const st=document.querySelector('#save-status');if(st)st.textContent=`Saved to ${b.textContent}`;toast(`Saved to ${b.textContent}`);}catch(_){toast('Save failed.');}});}
async function deleteDoc(id){if(!confirm('Delete this document permanently from the ScriptSmith Library? This cannot be undone.'))return;if(await deleteLibraryDocument(id)){toast('Document deleted.');const card=document.querySelector(`.project-card[data-library-id="${CSS.escape(id)}"]`);card?.closest('.ss-doc-wrap')?.remove();}}
function decorateDeletes(){document.querySelectorAll('.project-card[data-library-id]').forEach(card=>{if(card.dataset.ssDelete)return;card.dataset.ssDelete='1';const wrap=document.createElement('div');wrap.className='ss-doc-wrap';card.parentNode.insertBefore(wrap,card);wrap.appendChild(card);const b=document.createElement('button');b.type='button';b.className='theme-button ss-delete-doc';b.textContent='Delete Document';b.dataset.ssDeleteId=card.dataset.libraryId;wrap.appendChild(b);});}
function newTimelineEvent(panel){const d=getCurrentDocument();d.metadata=d.metadata||{};d.metadata.timeline=d.metadata.timeline||[];const ev={id:crypto.randomUUID(),title:'New event',date:'',summary:'',notes:''};d.metadata.timeline.push(ev);panel.innerHTML=`<div class="explorer-header"><div><button id="ss-timeline-cancel" class="theme-button">‹ Timeline</button><h1>New Timeline Event</h1></div></div><div class="record-form"><label>Event Name<input id="ss-event-title" value="${esc(ev.title)}"></label><label>Date<input id="ss-event-date" type="date"></label><label>Summary<textarea id="ss-event-summary"></textarea></label><label>Details<textarea id="ss-event-notes"></textarea></label><div class="ss-timeline-actions"><button id="ss-timeline-save" class="primary-action">Save Event</button><button id="ss-timeline-delete" class="theme-button">Delete Event</button></div></div>`;panel.querySelector('#ss-event-title').oninput=e=>ev.title=e.target.value;panel.querySelector('#ss-event-date').onchange=e=>ev.date=e.target.value;panel.querySelector('#ss-event-summary').oninput=e=>ev.summary=e.target.value;panel.querySelector('#ss-event-notes').oninput=e=>ev.notes=e.target.value;const returnToTimeline=()=>document.querySelector('.side-button[data-view="timeline"]')?.click();panel.querySelector('#ss-timeline-save').onclick=()=>{toast('Timeline event saved.');returnToTimeline();};panel.querySelector('#ss-timeline-cancel').onclick=()=>{d.metadata.timeline=d.metadata.timeline.filter(x=>x.id!==ev.id);returnToTimeline();};panel.querySelector('#ss-timeline-delete').onclick=()=>{d.metadata.timeline=d.metadata.timeline.filter(x=>x.id!==ev.id);returnToTimeline();};}
export function installEnhancements(){installPagination();document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.id==='save'){event.preventDefault();event.stopImmediatePropagation();saveMenu();return;}if(b.dataset.ssDeleteId){event.preventDefault();event.stopImmediatePropagation();deleteDoc(b.dataset.ssDeleteId);return;}if(b.id==='add-event'){event.preventDefault();event.stopImmediatePropagation();const p=document.querySelector('#workspace-panel');if(p)newTimelineEvent(p);return;}decorateDeletes();},true);const observer=new MutationObserver(decorateDeletes);observer.observe(document.body,{childList:true,subtree:true});setTimeout(decorateDeletes,150);}
