import { getCurrentDocument } from './document.js';
import { saveProject } from './filesystem.js';

const SETTINGS_KEY='scriptsmith-settings';
const defaults={namedNoteBoxes:true,autosave:true,autosaveInterval:10,spellcheck:true,showPageNumbers:true,sessionStats:true,readingMode:'comfortable'};
const loadSettings=()=>({...defaults,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')});
const saveSettings=s=>localStorage.setItem(SETTINGS_KEY,JSON.stringify(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));

export function installFinalFixes(){
  const observe=new MutationObserver(()=>{injectSidebar();enhanceToolbar();enhanceRecords();enhanceTimeline();});
  observe.observe(document.body,{childList:true,subtree:true});
  document.addEventListener('click',handleClick,true);
  setTimeout(()=>{injectSidebar();enhanceToolbar();},50);
}
function injectSidebar(){
 const sidebar=document.querySelector('.sidebar'); if(!sidebar)return;
 const labels=[['notes','Notes'],['toc','Table of Contents'],['prologue','Prologue'],['epilogue','Epilogue'],['universal-timeline','Universal Timeline']];
 const anchor=sidebar.querySelector('.sidebar-spacer');
 labels.forEach(([v,l])=>{if(sidebar.querySelector(`[data-view="${v}"]`))return;const b=document.createElement('button');b.className='side-button';b.dataset.view=v;b.textContent=l;sidebar.insertBefore(b,anchor);});
}
function enhanceToolbar(){
 const t=document.querySelector('.toolbar');if(!t||t.dataset.finalFixed)return;
 t.dataset.finalFixed='1';
 const add=(id,text,title,fn)=>{let b=document.getElementById(id);if(!b){b=document.createElement('button');b.id=id;b.className='toolbar-action';b.textContent=text;t.appendChild(b);}b.title=title;b.setAttribute('aria-label',title);b.onclick=fn;};
 add('heading-style','H','Heading style — choose a heading level',()=>{const n=prompt('Heading level: 1, 2, 3, or 0 for normal text','1');if(n===null)return;document.execCommand(n==='0'?'formatBlock':'formatBlock',false,n==='0'?'p':`h${Math.min(6,Math.max(1,Number(n)||1))}`);});
 add('line-spacing','↕','Line spacing: Single, 1.15, 1.5, Double',()=>chooseSpacing());
 add('spellcheck-toggle','✓','Spellcheck on/off',()=>{const e=document.querySelector('#editor');if(e)e.spellcheck=!e.spellcheck;});
 add('page-number-toggle','#','Page numbers on/off',()=>togglePageNumbers());
 add('header-button','H/F','Header and Footer',()=>editHeaderFooter());
 add('page-break','¶','Insert or remove page break markers',()=>insertPageBreak());
 add('find-breaks','Find ¶','Find page breaks',()=>findBreaks());
 [document.querySelector('#size')].forEach(s=>{if(s){s.style.fontSize='16px';s.style.minWidth='64px';}});
 const f=document.querySelector('#font');if(f)f.style.minWidth='190px';
}
function chooseSpacing(){const v=prompt('Line spacing: 1 = Single, 1.15, 1.5, 2 = Double, 2.5, 3 = Triple','1.5');if(v===null)return;const n=Number(v);if(!n)return;document.execCommand('formatBlock',false,'p');document.querySelector('#editor')?.style.setProperty('line-height',String(n));}
function togglePageNumbers(){const d=getCurrentDocument();d.metadata=d.metadata||{};d.metadata.manuscriptPreferences=d.metadata.manuscriptPreferences||{};d.metadata.manuscriptPreferences.pageNumbers=!d.metadata.manuscriptPreferences.pageNumbers;}
function editHeaderFooter(){const d=getCurrentDocument();d.metadata=d.metadata||{};d.metadata.manuscriptPreferences=d.metadata.manuscriptPreferences||{};const h=prompt('Header text (leave blank for none):',d.metadata.manuscriptPreferences.header||'');if(h===null)return;const f=prompt('Footer text (leave blank for none):',d.metadata.manuscriptPreferences.footer||'');if(f===null)return;d.metadata.manuscriptPreferences.header=h;d.metadata.manuscriptPreferences.footer=f;}
function insertPageBreak(){const e=document.querySelector('#editor');if(!e)return;const s=window.getSelection();const r=s?.rangeCount?s.getRangeAt(0):null;const el=document.createElement('div');el.className='scriptsmith-page-break';el.dataset.pageBreak='true';el.contentEditable='false';el.textContent='¶ Page Break — click to remove';el.title='Page break — click to remove';if(r){r.deleteContents();r.insertNode(el);}else e.appendChild(el);el.onclick=()=>el.remove();}
function findBreaks(){const breaks=[...document.querySelectorAll('.scriptsmith-page-break')];if(!breaks.length){alert('No page breaks in this manuscript.');return;}breaks[0].scrollIntoView({behavior:'smooth',block:'center'});breaks.forEach((b,i)=>b.classList.toggle('scriptsmith-break-found',i===0));}
function handleClick(ev){
 const b=ev.target.closest('button');if(!b)return;
 if(b.id==='home-settings'||b.dataset.view==='settings'){ev.preventDefault();ev.stopImmediatePropagation();showSettings();return;}
 if(b.dataset.view==='notes'){ev.preventDefault();ev.stopImmediatePropagation();showNotes();return;}
 if(b.dataset.view==='toc'){ev.preventDefault();ev.stopImmediatePropagation();showTOC();return;}
 if(b.dataset.view==='prologue'){ev.preventDefault();ev.stopImmediatePropagation();showFrontMatter('prologue');return;}
 if(b.dataset.view==='epilogue'){ev.preventDefault();ev.stopImmediatePropagation();showFrontMatter('epilogue');return;}
 if(b.dataset.view==='universal-timeline'){ev.preventDefault();ev.stopImmediatePropagation();showUniversalTimeline();return;}
 if(b.id==='save'){ev.preventDefault();ev.stopImmediatePropagation();showSaveOptions();return;}
 if(b.id==='records-back' || b.id==='records-delete')return;
}
function panel(title,html){const p=document.querySelector('#workspace-panel');if(!p)return;document.querySelector('#editor').hidden=true;document.querySelector('.toolbar').hidden=true;document.querySelector('.statusbar').hidden=true;p.hidden=false;p.innerHTML=`<div class="explorer-header"><div><h1>${title}</h1></div></div>${html}`;return p;}
function showSettings(){
 const s=loadSettings();const p=panel('Settings',`<div class="settings-grid"><label><input id="set-named-notes" type="checkbox" ${s.namedNoteBoxes?'checked':''}> Allow note boxes to have custom names</label><label><input id="set-autosave" type="checkbox" ${s.autosave?'checked':''}> Automatic recovery/autosave</label><label>Autosave interval <select id="set-interval"><option>5</option><option>10</option><option>30</option><option>60</option></select> seconds</label><label><input id="set-spellcheck" type="checkbox" ${s.spellcheck?'checked':''}> Spellcheck by default</label><label><input id="set-pages" type="checkbox" ${s.showPageNumbers?'checked':''}> Show page numbers by default</label><label><input id="set-session" type="checkbox" ${s.sessionStats?'checked':''}> Track writing sessions</label><label>Reading mode <select id="set-reading"><option value="comfortable">Comfortable</option><option value="focused">Focused</option><option value="page">Page</option></select></label></div><button id="settings-save" class="primary-action">Save Settings</button>`);
 if(!p)return;document.querySelector('#set-interval').value=String(s.autosaveInterval);document.querySelector('#set-reading').value=s.readingMode;
 document.querySelector('#settings-save').onclick=()=>{s.namedNoteBoxes=document.querySelector('#set-named-notes').checked;s.autosave=document.querySelector('#set-autosave').checked;s.autosaveInterval=Number(document.querySelector('#set-interval').value);s.spellcheck=document.querySelector('#set-spellcheck').checked;s.showPageNumbers=document.querySelector('#set-pages').checked;s.sessionStats=document.querySelector('#set-session').checked;s.readingMode=document.querySelector('#set-reading').value;saveSettings(s);alert('Settings saved.');};
}
function showNotes(){const d=getCurrentDocument();d.metadata=d.metadata||{};d.metadata.notes=Array.isArray(d.metadata.notes)?d.metadata.notes:[];const p=panel('Notes',`<div class="explorer-header"><div></div><button id="add-note-box" class="primary-action">+ New Note Box</button></div><div id="note-boxes"></div>`);if(!p)return;renderNotes(p);document.querySelector('#add-note-box').onclick=()=>{d.metadata.notes.push({id:crypto.randomUUID(),name:'New Note',content:''});renderNotes(p);};}
function renderNotes(p){const d=getCurrentDocument(),notes=d.metadata.notes||[],named=loadSettings().namedNoteBoxes;const el=document.querySelector('#note-boxes');el.innerHTML=notes.map((n,i)=>`<section class="note-box"><div><input class="note-name" value="${esc(n.name||'Note')}" ${named?'':'hidden'}><button class="theme-button note-delete" data-i="${i}">Delete</button></div><textarea class="note-content" data-i="${i}" placeholder="Write a note…">${esc(n.content||'')}</textarea></section>`).join('')||'<div class="feature-placeholder">No notes yet. Add a note box.</div>';el.querySelectorAll('.note-name').forEach(x=>x.oninput=()=>notes[Number(x.closest('.note-box').querySelector('.note-delete').dataset.i)].name=x.value);el.querySelectorAll('.note-content').forEach(x=>x.oninput=()=>notes[Number(x.dataset.i)].content=x.value);el.querySelectorAll('.note-delete').forEach(x=>x.onclick=()=>{notes.splice(Number(x.dataset.i),1);renderNotes(p);});}
function showTOC(){const d=getCurrentDocument();const chapters=d.metadata?.chapters||[];const p=panel('Table of Contents',`<div class="toc-controls"><label>Mode <select id="toc-mode"><option value="automatic">Automatic from chapters</option><option value="manual">Manual</option></select></label><button id="toc-save" class="primary-action">Save TOC</button></div><div id="toc-list"></div>`);const mode=d.metadata.tableOfContents?.mode||'automatic';document.querySelector('#toc-mode').value=mode;const list=document.querySelector('#toc-list');list.innerHTML=mode==='automatic'?chapters.map((c,i)=>`<div>${i+1}. ${esc(c.title)}</div>`).join(''):chapters.map((c,i)=>`<input class="toc-entry" data-i="${i}" value="${esc(d.metadata.tableOfContents.entries?.[i]||c.title)}">`).join('');document.querySelector('#toc-mode').onchange=()=>showTOC();document.querySelector('#toc-save').onclick=()=>{d.metadata.tableOfContents={mode:document.querySelector('#toc-mode').value,entries:[...document.querySelectorAll('.toc-entry')].map(x=>x.value)};alert('Table of Contents saved.');};}
function showFrontMatter(type){const d=getCurrentDocument();d.metadata=d.metadata||{};d.metadata[type]=d.metadata[type]||{enabled:false,title:type[0].toUpperCase()+type.slice(1),content:''};const x=d.metadata[type];const p=panel(type==='prologue'?'Prologue':'Epilogue',`<label>Title<input id="fm-title" value="${esc(x.title)}"></label><label>Content<textarea id="fm-content" rows="18">${esc(x.content||'')}</textarea></label><button id="fm-template" class="theme-button">Insert Template</button> <button id="fm-save" class="primary-action">Save</button><details><summary>What is this?</summary><p>${type==='prologue'?'A prologue comes before Chapter 1 and can establish context, voice, history, or a hook.':'An epilogue comes after the main story and can show aftermath, closure, or a glimpse of what comes next.'}</p></details>`);document.querySelector('#fm-template').onclick=()=>document.querySelector('#fm-content').value=type==='prologue'?'Before the story begins…\n\n[Set the context, voice, or event that prepares the reader.]':'After the story…\n\n[Show the aftermath, resolution, or future of the characters.]';document.querySelector('#fm-save').onclick=()=>{x.title=document.querySelector('#fm-title').value;x.content=document.querySelector('#fm-content').value;x.enabled=Boolean(x.content.trim());alert(`${type==='prologue'?'Prologue':'Epilogue'} saved.`);};}
function showUniversalTimeline(){const key='scriptsmith-universal-library';let u={characters:[],locations:[],timeline:[]};try{u={...u,...JSON.parse(localStorage.getItem(key)||'{}')}}catch(_){}u.timeline=u.timeline||[];const p=panel('Universal Timeline',`<div class="explorer-header"><div><p>Add events manually and reorder them vertically.</p></div><button id="universal-add-event" class="primary-action">+ Add Event</button></div><div id="universal-events"></div>`);const render=()=>{document.querySelector('#universal-events').innerHTML=u.timeline.map((e,i)=>`<div class="timeline-row" draggable="true" data-i="${i}"><button data-up="${i}">↑</button><button data-down="${i}">↓</button><input data-name="${i}" value="${esc(e.title||e.name||'Event')}"><input data-date="${i}" value="${esc(e.date||'')}" placeholder="Date"><button data-del="${i}">Delete</button></div>`).join('')||'<div class="feature-placeholder">No universal events yet.</div>';document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>move(Number(b.dataset.up),-1));document.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>move(Number(b.dataset.down),1));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{u.timeline.splice(Number(b.dataset.del),1);save();render();});document.querySelectorAll('[data-name]').forEach(b=>b.oninput=()=>u.timeline[Number(b.dataset.name)].title=b.value);document.querySelectorAll('[data-date]').forEach(b=>b.oninput=()=>u.timeline[Number(b.dataset.date)].date=b.value);};const save=()=>localStorage.setItem(key,JSON.stringify(u));const move=(i,d)=>{const j=i+d;if(j<0||j>=u.timeline.length)return;[u.timeline[i],u.timeline[j]]=[u.timeline[j],u.timeline[i]];save();render();};document.querySelector('#universal-add-event').onclick=()=>{u.timeline.push({id:crypto.randomUUID(),title:'New Event',date:''});save();render();};render();}
function showSaveOptions(){const d=getCurrentDocument();const p=panel('Save',`<div class="save-choice"><button id="save-whole" class="primary-action">Save Whole Manuscript</button><button id="save-chapter" class="theme-button">Save Current Writing as Chapter</button><button id="save-research" class="theme-button">Save as Research</button><button id="save-doc" class="theme-button">Save as Whole Document</button></div>`);document.querySelector('#save-whole').onclick=async()=>{await saveProject(d);alert('Saved to ScriptSmith Library.');};document.querySelector('#save-chapter').onclick=async()=>{const title=prompt('Chapter title:','New Chapter');if(!title)return;d.metadata=d.metadata||{};d.metadata.chapters=d.metadata.chapters||[];d.metadata.chapters.push({id:crypto.randomUUID(),title,content:d.content||''});await saveProject(d);alert(`Saved as chapter: ${title}`);};document.querySelector('#save-research').onclick=async()=>{d.metadata=d.metadata||{};d.metadata.research=d.metadata.research||[];d.metadata.research.push({id:crypto.randomUUID(),name:d.title||'Research',summary:'',content:d.content||''});await saveProject(d);alert('Saved as research.');};document.querySelector('#save-doc').onclick=async()=>{await saveProject(d);alert('Saved as whole document.');};}
function enhanceRecords(){const form=document.querySelector('.record-form');if(!form||form.dataset.finalFixed)return;const h=document.querySelector('#workspace-panel h1')?.textContent||'';if(!/Character/.test(h))return;form.dataset.finalFixed='1';const fields=[['personality','Personality / temperament'],['psychology','Psychology / defense mechanisms'],['fears','Fears'],['desires','Core desires / motivations'],['values','Values / beliefs'],['flaws','Flaws / weaknesses'],['strengths','Strengths'],['backstory','Full backstory'],['adventure','Adventure / experiences'],['family','Family tree / relatives'],['relationships','Relationships'],['favoriteMusic','Favorite music / songs / artists'],['favoriteBooks','Favorite books'],['favoriteShows','Favorite shows / films'],['fashion','Fashion / clothing style'],['hobbies','Hobbies / interests'],['secrets','Secrets'],['characterArc','Character arc / growth']];const box=document.createElement('div');box.className='character-bible-fields';box.innerHTML='<h2>Character Bible</h2>'+fields.map(([k,l])=>`<label>${l}<textarea data-char-field="${k}" rows="3"></textarea></label>`).join('');form.appendChild(box);const r=findRecord();fields.forEach(([k])=>{const x=form.querySelector(`[data-char-field="${k}"]`);if(x){x.value=r?.[k]||'';x.oninput=()=>{if(r)r[k]=x.value;};}});}
function findRecord(){const name=document.querySelector('#record-name')?.value;const d=getCurrentDocument();return [...(d.metadata?.characters||[])].find(r=>r.name===name)||null;}
function enhanceTimeline(){const p=document.querySelector('#workspace-panel');if(!p)return;const h=p.querySelector('h1')?.textContent||'';if(!/Timeline/.test(h)||p.dataset.finalTimeline)return;p.dataset.finalTimeline='1';if(!p.querySelector('#add-universal-timeline-event')){const b=document.createElement('button');b.id='add-universal-timeline-event';b.className='primary-action';b.textContent='+ Add Event';b.onclick=()=>{const d=getCurrentDocument();d.metadata=d.metadata||{};d.metadata.timeline=d.metadata.timeline||[];d.metadata.timeline.push({id:crypto.randomUUID(),title:'New Event',date:''});const row=document.createElement('div');row.className='timeline-row';row.textContent='New Event';p.appendChild(row);};p.querySelector('.explorer-header')?.appendChild(b);}}
