import { getCurrentDocument } from './document.js';
import { saveProject } from './filesystem.js';

const UKEY='scriptsmith-universal-library';
const SETTINGS_KEY='scriptsmith-settings';
const getSettings=()=>{try{return {...{namedNoteBoxes:true,autosave:true,autosaveInterval:10,spellcheck:true,showPageNumbers:true,sessionStats:true,readingMode:'comfortable'},...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch(_){return {namedNoteBoxes:true,autosave:true,autosaveInterval:10,spellcheck:true,showPageNumbers:true,sessionStats:true,readingMode:'comfortable'}}};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uni=()=>{try{return {...{characters:[],locations:[],timeline:[]},...JSON.parse(localStorage.getItem(UKEY)||'{}')}}catch(_){return {characters:[],locations:[],timeline:[]}}};
const saveUni=u=>localStorage.setItem(UKEY,JSON.stringify(u));

export function installPhase2Fixes(){
  const observer=new MutationObserver(()=>{fixStatisticsHighlight();labelToolbarButtons();installPageLayout();ensureUniversalAccess();});
  observer.observe(document.body,{childList:true,subtree:true});
  document.addEventListener('click',onClick,true);
  setTimeout(()=>{fixStatisticsHighlight();labelToolbarButtons();installPageLayout();ensureUniversalAccess();},100);
}

function fixStatisticsHighlight(){document.querySelectorAll('.side-button[data-view]').forEach(b=>{if(b.dataset.view==='statistics'&&!b.classList.contains('active')){const panel=document.querySelector('#workspace-panel h1');if(panel&&panel.textContent.trim()==='Statistics')b.classList.add('active');}});}
function labelToolbarButtons(){const map={'spellcheck-toggle':['✓','Spellcheck','Turn spellcheck on or off'],'page-number-toggle':['#','Page Numbers','Turn page numbering on or off'],'heading-style':['H','Heading Styles','Choose a saved heading style or create one']};Object.entries(map).forEach(([id,[text,label,title]])=>{const b=document.getElementById(id);if(!b)return;b.textContent=`${text} ${label}`;b.title=title;b.setAttribute('aria-label',title);});const no=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='No');if(no){no.textContent='No / Cancel';no.title='Choose No or cancel this action';}}
function installPageLayout(){const e=document.querySelector('#editor');if(!e||e.dataset.phase2Pages)return;e.dataset.phase2Pages='1';const apply=()=>{e.classList.add('paginated-manuscript');if(!e.querySelector('.scriptsmith-page')){const children=[...e.children];if(children.length){children.forEach(c=>{if(c.classList.contains('scriptsmith-page'))return;c.classList.add('manuscript-flow-content');});}}};apply();}
function onClick(ev){const b=ev.target.closest('button');if(!b)return;
  if(b.id==='universal-characters'){ev.preventDefault();ev.stopImmediatePropagation();showUniversalCharacters();return;}
  if(b.id==='universal-timeline-home'){ev.preventDefault();ev.stopImmediatePropagation();showUniversalTimelineHome();return;}
  if(b.id==='save'){ev.preventDefault();ev.stopImmediatePropagation();saveMenu();return;}
  if(b.id==='heading-style'){ev.preventDefault();ev.stopImmediatePropagation();headingMenu();return;}
}
function modal(title,html){let m=document.getElementById('phase2-modal');if(!m){m=document.createElement('div');m.id='phase2-modal';m.className='phase2-modal';document.body.appendChild(m);}m.innerHTML=`<div class="phase2-dialog"><div class="phase2-dialog-head"><h2>${title}</h2><button id="phase2-close" aria-label="Close">×</button></div>${html}</div>`;m.hidden=false;document.getElementById('phase2-close').onclick=()=>m.hidden=true;return m;}
function headingMenu(){const d=getCurrentDocument();d.metadata=d.metadata||{};d.metadata.headingStyles=Array.isArray(d.metadata.headingStyles)?d.metadata.headingStyles:[];const styles=d.metadata.headingStyles;const m=modal('Heading Styles',`<div class="heading-style-list">${styles.map((s,i)=>`<button class="theme-button heading-pick" data-i="${i}">${esc(s.name||'Header '+(i+1))}</button>`).join('')||'<p>No custom heading styles yet.</p>'}</div><button id="new-heading-style" class="primary-action">Create New</button>`);m.querySelectorAll('.heading-pick').forEach(b=>b.onclick=()=>{const s=styles[Number(b.dataset.i)];document.execCommand('formatBlock',false,s.tag||'h2');m.hidden=true;});m.querySelector('#new-heading-style').onclick=()=>{const name=prompt('Name this heading style:',`Header ${styles.length+1}`);if(!name)return;const tag=prompt('Heading level (1-6):','2')||'2';styles.push({name,tag:`h${Math.min(6,Math.max(1,Number(tag)||2))}`});m.hidden=true;headingMenu();};}
async function saveMenu(){const d=getCurrentDocument();const active=window.__scriptSmithActiveChapter;const u=uni();const characterNames=(d.metadata?.characters||[]).filter(x=>x&&x.name);const m=modal('Save',`<p>Choose how to save this work inside ScriptSmith.</p><div class="save-options"><button id="p2-save-manuscript" class="primary-action">Save to Manuscript</button><button id="p2-save-both" class="theme-button">Save to Manuscript + Universal Characters</button><button id="p2-save-whole" class="theme-button">Save Whole Document</button></div>`);m.querySelector('#p2-save-manuscript').onclick=async()=>{await saveProject(d);m.hidden=true;setSaveStatus('Saved to ScriptSmith Library');};m.querySelector('#p2-save-both').onclick=async()=>{characterNames.forEach(c=>{const old=u.characters.find(x=>x.id===c.id||x.name===c.name);if(old)Object.assign(old,structuredClone(c));else u.characters.push(structuredClone(c));});saveUni(u);await saveProject(d);m.hidden=true;setSaveStatus('Saved to Manuscript + Universal Characters');};m.querySelector('#p2-save-whole').onclick=async()=>{await saveProject(d);m.hidden=true;setSaveStatus('Saved to ScriptSmith Library');};}
function setSaveStatus(text){const s=document.querySelector('#save-status');if(s)s.textContent=text;}
function showUniversalCharacters(){const u=uni();const m=modal('Universal Characters',`<div class="universal-character-toolbar"><button id="uc-add" class="primary-action">+ Add Universal Character</button></div><div id="uc-list">${u.characters.length?u.characters.map(c=>`<button class="record-row theme-card" data-uc="${c.id}"><strong>${esc(c.name||'Untitled')}</strong><span>${esc(c.summary||'Full Character Profile')}</span></button>`).join(''):'<p>No universal characters yet.</p>'}</div>`);m.querySelector('#uc-add').onclick=()=>{const c={id:crypto.randomUUID(),name:'New Character',summary:''};u.characters.push(c);saveUni(u);showUniversalCharacterProfile(c.id);};m.querySelectorAll('[data-uc]').forEach(b=>b.onclick=()=>showUniversalCharacterProfile(b.dataset.uc));}
function showUniversalCharacterProfile(id){const u=uni(),c=u.characters.find(x=>x.id===id);if(!c)return;const fields=[['personality','Personality / temperament'],['psychology','Psychology / defense mechanisms'],['fears','Fears'],['desires','Core desires / motivations'],['values','Values / beliefs'],['flaws','Flaws / weaknesses'],['strengths','Strengths'],['backstory','Full backstory'],['adventure','Adventure / experiences'],['family','Family tree / relatives'],['relationships','Relationships'],['favoriteMusic','Favorite music / songs / artists'],['favoriteBooks','Favorite books'],['favoriteShows','Favorite shows / films'],['fashion','Fashion / clothing style'],['hobbies','Hobbies / interests'],['secrets','Secrets'],['characterArc','Character arc / growth']];const m=modal('Universal Character Profile',`<div class="character-profile-wide"><label>Name<input id="uc-name" value="${esc(c.name||'')}"></label>${fields.map(([k,l])=>`<label>${l}<textarea data-uc-field="${k}" rows="4">${esc(c[k]||'')}</textarea></label>`).join('')}</div><button id="uc-save" class="primary-action">Save Character</button>`);m.querySelector('#uc-save').onclick=()=>{c.name=m.querySelector('#uc-name').value||'Untitled Character';fields.forEach(([k])=>c[k]=m.querySelector(`[data-uc-field="${k}"]`).value);c.summary=c.personality||c.backstory||'';saveUni(u);m.hidden=true;showUniversalCharacters();};}
function showUniversalTimelineHome(){const u=uni();const m=modal('Universal Timeline',`<p>Universal events can be added here and referenced from individual manuscripts.</p><button id="ut-add" class="primary-action">+ Add Event</button><div id="ut-list">${u.timeline.map((e,i)=>`<div class="timeline-row"><input data-ut-title="${i}" value="${esc(e.title||'Event')}"><input data-ut-date="${i}" value="${esc(e.date||'')}" placeholder="Date"><button data-ut-del="${i}">Delete</button></div>`).join('')}</div>`);m.querySelector('#ut-add').onclick=()=>{u.timeline.push({id:crypto.randomUUID(),title:'New Event',date:''});saveUni(u);showUniversalTimelineHome();};m.querySelectorAll('[data-ut-title]').forEach(x=>x.oninput=()=>{u.timeline[Number(x.dataset.utTitle)].title=x.value;saveUni(u);});m.querySelectorAll('[data-ut-date]').forEach(x=>x.oninput=()=>{u.timeline[Number(x.dataset.utDate)].date=x.value;saveUni(u);});m.querySelectorAll('[data-ut-del]').forEach(x=>x.onclick=()=>{u.timeline.splice(Number(x.dataset.utDel),1);saveUni(u);showUniversalTimelineHome();});}
function ensureUniversalAccess(){const home=document.querySelector('#home .universal-library');if(home&&!document.getElementById('universal-timeline-home')){const b=document.createElement('button');b.className='universal-card';b.id='universal-timeline-home';b.innerHTML='<strong>Universal Timeline</strong><span>Events shared across your stories</span>';home.appendChild(b);} }
