import { getCurrentDocument } from './document.js';
import { listLibraryDocuments, saveToLibrary } from './filesystem.js';
import { createBackup } from './backups.js';

const UNIVERSAL_KEY='scriptsmith-universal-library';
const BACKUP_INTERVAL=5*60*1000;

function universal(){try{return JSON.parse(localStorage.getItem(UNIVERSAL_KEY)||'{"characters":[],"locations":[],"timeline":[]}')}catch(_){return {characters:[],locations:[],timeline:[]}}}
function currentPrefs(){const d=getCurrentDocument();if(!d)return null;d.metadata=d.metadata||{};d.metadata.manuscriptPreferences={fontFamily:'Georgia',fontSize:12,lineSpacing:1,header:'',footer:'',pageNumbers:false,...(d.metadata.manuscriptPreferences||{})};if(d.metadata.manuscriptPreferences.lineHeight&&!d.metadata.manuscriptPreferences.lineSpacing)d.metadata.manuscriptPreferences.lineSpacing=Number(d.metadata.manuscriptPreferences.lineHeight)||1;return d.metadata.manuscriptPreferences;}
function toast(message,kind='success'){let el=document.querySelector('#sprint19-toast');if(!el){el=document.createElement('div');el.id='sprint19-toast';document.body.appendChild(el)}el.className=`sprint19-toast ${kind}`;el.textContent=message;el.hidden=false;clearTimeout(el._timer);el._timer=setTimeout(()=>{el.hidden=true},2400)}
function markDirty(){const s=document.querySelector('#save-status');if(s)s.textContent='Unsaved changes'}
function applyManuscriptPreferences(){const editor=document.querySelector('#editor'),toolbar=document.querySelector('#font'),size=document.querySelector('#size'),spacing=document.querySelector('#line-spacing'),p=currentPrefs();if(!p)return;if(editor){editor.style.fontFamily=p.fontFamily||'Georgia';editor.style.fontSize=`${p.fontSize||12}px`;editor.style.lineHeight=String(p.lineSpacing||1)}if(toolbar&&p.fontFamily)toolbar.value=p.fontFamily;if(size&&p.fontSize)size.value=String(p.fontSize);if(spacing&&p.lineSpacing)spacing.value=String(p.lineSpacing)}
function addUniversalTimelineCard(){const library=document.querySelector('.universal-library');if(!library||document.querySelector('#universal-timeline'))return;const card=document.createElement('button');card.className='universal-card';card.id='universal-timeline';card.innerHTML='<strong>Universal Timeline</strong><span>Events shared across all your stories</span>';card.onclick=showUniversalTimeline;library.appendChild(card)}
async function showUniversalTimeline(){const data=universal(),docs=await listLibraryDocuments(),events=[...(data.timeline||[])];docs.forEach(doc=>(doc.metadata?.timeline||[]).forEach(event=>events.push({...event,sourceTitle:doc.title||'Untitled manuscript'})));events.sort((a,b)=>String(a.order??a.date??'').localeCompare(String(b.order??b.date??'')));let modal=document.querySelector('#sprint19-timeline-modal');if(!modal){modal=document.createElement('div');modal.id='sprint19-timeline-modal';document.body.appendChild(modal)}modal.innerHTML=`<div class="sprint19-modal-backdrop"><section class="sprint19-modal"><header><div><h2>Universal Timeline</h2><p>One chronological view across your ScriptSmith library.</p></div><button id="s19-close" class="theme-button">Close</button></header><div class="sprint19-timeline-list">${events.length?events.map(e=>`<article><time>${escapeHtml(e.date||'Undated')}</time><div><strong>${escapeHtml(e.title||e.name||'Untitled event')}</strong><span>${escapeHtml(e.description||e.summary||'')}${e.sourceTitle?` · ${escapeHtml(e.sourceTitle)}`:''}</span></div></article>`).join(''):'<div class="feature-placeholder">No timeline events exist yet.</div>'}</div></section></div>`;modal.hidden=false;modal.querySelector('#s19-close').onclick=()=>{modal.hidden=true}}
function enhanceLibrarySearch(){const section=document.querySelector('.library-section');if(!section||document.querySelector('#sprint19-library-search'))return;const heading=section.querySelector('.section-heading');if(!heading)return;const input=document.createElement('input');input.id='sprint19-library-search';input.className='sprint19-search';input.placeholder='Search your library…';input.setAttribute('aria-label','Search your library');heading.appendChild(input);input.oninput=()=>{const q=input.value.trim().toLowerCase();document.querySelectorAll('#library .project-card').forEach(card=>{card.hidden=!!q&&!card.innerText.toLowerCase().includes(q)})}}
function enhanceRecordView(panel){if(!panel||!panel.querySelector('.record-form')||panel.querySelector('.sprint19-record-actions'))return;const form=panel.querySelector('.record-form'),controls=[...form.querySelectorAll('input,textarea,select')];controls.forEach(c=>{c.readOnly=false;c.disabled=false});const actions=document.createElement('div');actions.className='sprint19-record-actions';actions.innerHTML='<button id="s19-save-record" class="primary-action">Save Changes</button><button id="s19-cancel-record" class="theme-button">Cancel</button>';form.appendChild(actions);const idFrom=(id)=>form.querySelector(`#${id}`)?.value||'';const saveButton=actions.querySelector('#s19-save-record');saveButton.onclick=async()=>{const d=getCurrentDocument();const heading=panel.querySelector('.explorer-header h1');const titleField=form.querySelector('#record-name');const recordName=idFrom('record-name');const keys=['characters','locations','research'];let record=null;for(const key of keys){record=(d.metadata?.[key]||[]).find(r=>r.id===panel.dataset.recordId||r.id===form.dataset.recordId||r.name===heading?.textContent?.trim());if(record){record.name=recordName||record.name;record.summary=idFrom('record-summary');record.notes=idFrom('record-notes');break}}if(!record){const all=[...(d.metadata?.characters||[]),...(d.metadata?.locations||[]),...(d.metadata?.research||[])];record=all.find(r=>r.id===panel.dataset.recordId||r.name===heading?.textContent?.trim());if(record){record.name=recordName||record.name;record.summary=idFrom('record-summary');record.notes=idFrom('record-notes')}}d.updatedAt=new Date().toISOString();await saveToLibrary(d);markDirty();toast('Changes saved to this manuscript');};actions.querySelector('#s19-cancel-record').onclick=()=>{toast('Edit cancelled');window.dispatchEvent(new CustomEvent('scriptsmith:record-cancel'))}}
function enhanceReadingMode(panel){if(!panel||panel.querySelector('.sprint19-reading'))return;const title=panel.querySelector('.explorer-header h1');if(!title||!/Characters|Locations/i.test(title.textContent||''))return;const button=document.createElement('button');button.className='theme-button sprint19-reading';button.textContent='Reading Mode';panel.querySelector('.explorer-header')?.appendChild(button);button.onclick=()=>{panel.classList.toggle('sprint19-reader');button.textContent=panel.classList.contains('sprint19-reader')?'Exit Reading Mode':'Reading Mode'}}
function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function runAutomaticBackup(){try{const doc=getCurrentDocument();if(doc)await createBackup(doc)}catch(_) {}}
export function installSprint19(){window.addEventListener('scriptsmith:saved',()=>toast('Saved to your ScriptSmith library'));const observer=new MutationObserver(()=>{addUniversalTimelineCard();enhanceLibrarySearch();applyManuscriptPreferences();const panel=document.querySelector('#workspace-panel');if(panel){enhanceRecordView(panel);enhanceReadingMode(panel)}});observer.observe(document.body,{childList:true,subtree:true});addUniversalTimelineCard();enhanceLibrarySearch();window.setInterval(runAutomaticBackup,BACKUP_INTERVAL)}
