import { getCurrentDocument } from './document.js';
import { saveProject } from './filesystem.js';
import { createFontPicker } from './font-picker.js';
const SETTINGS_KEY='scriptsmith-settings-v2',LAYOUT_KEY='scriptsmith-layout-v1';
const PAPERS={Letter:['8.5in','11in'],A4:['8.27in','11.69in'],A5:['5.83in','8.27in'],Legal:['8.5in','14in'],Executive:['7.25in','10.5in'],'5 × 8':['5in','8in'],'5.25 × 8':['5.25in','8in'],'6 × 9':['6in','9in'],'7 × 10':['7in','10in']};
const MARGINS={Normal:['1in','1in','1in','1in'],Narrow:['.5in','.5in','.5in','.5in'],Moderate:['1in','.75in','1in','.75in'],Wide:['1in','2in','1in','2in']};
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const THEMES=[['classic','Snyder Scriptorium'],['modern','Modern'],['colorful','Colorful'],['bw','Black & white']];
const THEME_VALUES=THEMES.map(t=>t[0]);
const ACCENT_PRESETS=['#c2410c','#7c3aed','#0d9488','#db2777','#16a34a','#2563eb','#d97706','#9333ea'];
const defaults=()=>({autosave:true,autosaveInterval:10,theme:'classic',themeFont:'Inter',showUniverses:true,accentColor:''});
function settings(){try{return {...defaults(),...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch{return defaults()}}
function write(s){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify({...defaults(),...s}))}catch(_) {}}
function hexRgb(h){h=String(h||'').replace('#','');if(h.length===3)h=h.split('').map(c=>c+c).join('');const n=parseInt(h,16);return [n>>16&255,n>>8&255,n&255]}
function rgbHex(r,g,b){const c=v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,'0');return '#'+c(r)+c(g)+c(b)}
function shade(hex,amt){const [r,g,b]=hexRgb(hex),t=amt<0?0:255,p=Math.abs(amt);return rgbHex(r+(t-r)*p,g+(t-g)*p,b+(t-b)*p)}
function applyTheme(){const s=settings(),theme=THEME_VALUES.includes(s.theme)?s.theme:'classic',b=document.body;THEME_VALUES.forEach(v=>b.classList.toggle('ss-theme-'+v,v===theme));b.classList.add('ss-theme');if(theme==='colorful'&&/^#[0-9a-fA-F]{6}$/.test(s.accentColor||'')){b.style.setProperty('--ss-accent',s.accentColor);b.style.setProperty('--ss-accent-2',shade(s.accentColor,-0.35));b.style.setProperty('--ss-surface',shade(s.accentColor,0.9));b.style.setProperty('--ss-border',shade(s.accentColor,0.7));}else{b.style.removeProperty('--ss-accent');b.style.removeProperty('--ss-accent-2');b.style.removeProperty('--ss-surface');b.style.removeProperty('--ss-border');}document.documentElement.style.setProperty('--ss-editor-font',`'${String(s.themeFont||'Inter').replace(/'/g,"\\'")}'`)}
function layout(){try{return JSON.parse(localStorage.getItem(LAYOUT_KEY)||'{}')}catch{return {}}}
function applyLayout(){const p=document.querySelector('#ss-pages');if(!p)return;const s=layout(),paper=PAPERS[s.paper]||PAPERS.Letter,m=MARGINS[s.margin]||MARGINS.Normal;p.style.setProperty('--ss-page-width',paper[0]);p.style.setProperty('--ss-page-height',paper[1]);p.style.setProperty('--ss-margin-top',m[0]);p.style.setProperty('--ss-margin-right',m[1]);p.style.setProperty('--ss-margin-bottom',m[2]);p.style.setProperty('--ss-margin-left',m[3]);p.style.setProperty('--ss-gutter',(s.gutter||0)+'in');p.style.setProperty('--ss-columns',(s.columns||1)>1?s.columns:'auto');p.classList.toggle('ss-landscape',s.orientation==='landscape');p.classList.toggle('ss-book-fold',!!s.bookFold)}
function blank(){const a=document.querySelector('.ss-library-actions');if(!a||a.querySelector('.ss-blank-document-button'))return;const b=document.createElement('button');b.className='ss-button ss-blank-document-button';b.textContent='Blank Document';b.onclick=()=>a.querySelector('[data-action="new"]')?.click();a.appendChild(b)}
function categoryView(){const h=document.querySelector('#ss-project-heading'),g=document.querySelector('#ss-project-grid');if(!h||!g)return;const main=h.textContent.trim()==='All Manuscripts';g.querySelectorAll('.ss-project-card').forEach(x=>x.style.display=main?'none':'')}
function settingsUI(){const m=document.querySelector('.ss-modal');if(!m||m.querySelector('.ss-settings-extra'))return;const s=settings(),x=document.createElement('section');x.className='ss-settings-extra';x.innerHTML=`<h3>ScriptSmith Preferences</h3><div class="ss-settings-field"><label>Theme<select id="ss-theme-choice">${THEMES.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label></div><div class="ss-settings-field" id="ss-accent-field" style="display:none"><label>Choose your main color (Colorful theme)<div id="ss-accent-swatches" style="display:flex;gap:8px;flex-wrap:wrap;margin:8px 0"></div><input type="color" id="ss-accent-custom" value="${/^#[0-9a-fA-F]{6}$/.test(s.accentColor||'')?s.accentColor:'#c2410c'}" style="width:100%;height:44px;padding:2px" aria-label="Custom accent color"></label></div><div class="ss-settings-field"><label>Theme Font<span id="ss-font-choice-slot"></span></label></div><div class="ss-settings-field"><label>Save interval<select id="ss-autosave-choice"><option value="1">1 minute</option><option value="5">5 minutes</option><option value="10">10 minutes</option><option value="15">15 minutes</option><option value="30">30 minutes</option></select></label></div>`;m.appendChild(x);const t=x.querySelector('#ss-theme-choice'),i=x.querySelector('#ss-autosave-choice');t.value=s.theme;i.value=String(s.autosaveInterval);const af=x.querySelector('#ss-accent-field'),sw=x.querySelector('#ss-accent-swatches'),cc=x.querySelector('#ss-accent-custom');const syncAccentVis=()=>{af.style.display=t.value==='colorful'?'':'none'};sw.innerHTML=ACCENT_PRESETS.map(c=>`<button type="button" data-accent="${c}" title="${c}" style="width:40px;height:40px;border-radius:50%;background:${c};border:${(s.accentColor||'').toLowerCase()===c?'3px solid #000':'2px solid rgba(0,0,0,.15)'};cursor:pointer" aria-label="Use ${c}"></button>`).join('');const setAccent=c=>{const q=settings();q.accentColor=c;write(q);applyTheme();sw.querySelectorAll('[data-accent]').forEach(b=>b.style.border=b.dataset.accent.toLowerCase()===c.toLowerCase()?'3px solid #000':'2px solid rgba(0,0,0,.15)')};sw.querySelectorAll('[data-accent]').forEach(b=>b.onclick=()=>setAccent(b.dataset.accent));cc.oninput=()=>setAccent(cc.value);syncAccentVis();const fc=x.querySelector('#ss-font-choice-slot');if(fc)fc.replaceChildren(createFontPicker({current:s.themeFont||'Inter',onPick:v=>{const q=settings();q.themeFont=v;write(q);applyTheme();const editor=document.querySelector('.ss-page-content');if(editor)editor.style.fontFamily=`'${v.replace(/'/g,"\\'")}'`}}));t.onchange=()=>{const q=settings();q.theme=t.value;write(q);applyTheme();syncAccentVis()};i.onchange=()=>{const q=settings();q.autosaveInterval=Number(i.value);q.autosave=true;write(q)}}
function layoutUI(){const c=document.querySelector('#ss-ribbon-content');if(!c||!document.querySelector('[data-ribbon="layout"].active')||c.querySelector('.ss-layout-controls'))return;const s=layout(),g=document.createElement('div');g.className='ss-ribbon-group';g.innerHTML=`<b>Page Layout</b><div class="ss-layout-controls"><label>Paper<select id="ss-paper">${Object.keys(PAPERS).map(x=>`<option>${x}</option>`).join('')}</select></label><label>Margins<select id="ss-margin">${Object.keys(MARGINS).map(x=>`<option>${x}</option>`).join('')}</select></label><label>Orientation<select id="ss-orientation"><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label><label>Columns<select id="ss-columns"><option>1</option><option>2</option><option>3</option></select></label><label>Gutter<input id="ss-gutter" type="number" min="0" max="3" step=".05"></label><label>Book fold<input id="ss-book" type="checkbox"></label></div>`;c.appendChild(g);const p=g.querySelector('#ss-paper'),m=g.querySelector('#ss-margin'),o=g.querySelector('#ss-orientation'),n=g.querySelector('#ss-columns'),u=g.querySelector('#ss-gutter'),b=g.querySelector('#ss-book');p.value=s.paper||'Letter';m.value=s.margin||'Normal';o.value=s.orientation||'portrait';n.value=String(s.columns||1);u.value=s.gutter||0;b.checked=!!s.bookFold;const update=()=>{try{localStorage.setItem(LAYOUT_KEY,JSON.stringify({paper:p.value,margin:m.value,orientation:o.value,columns:Number(n.value),gutter:Number(u.value||0),bookFold:b.checked}))}catch(_){}applyLayout()};[p,m,o,n,u,b].forEach(e=>e.addEventListener('change',update));applyLayout()}
function tableDelete(e){const t=e.target.closest?.('.ss-editor-table');if(!t)return;document.querySelector('.ss-table-delete')?.remove();const b=document.createElement('button');b.className='ss-table-delete';b.textContent='Delete table';b.type='button';b.onclick=()=>{t.remove();b.remove()};const r=t.getBoundingClientRect();b.style.left=`${r.right-90}px`;b.style.top=`${r.top-32}px`;document.body.appendChild(b);setTimeout(()=>b.remove(),5000)}
let timer=null;function queueSave(){const w=document.querySelector('#ss-workspace'),d=getCurrentDocument(),s=settings();if(!w||w.hidden||!d||!d.metadata?.libraryCategory||!s.autosave)return;clearTimeout(timer);timer=setTimeout(async()=>{try{await saveProject(d);const z=document.querySelector('#ss-save-status');if(z)z.textContent='Saved'}catch{}},Math.max(500,Number(s.autosaveInterval||10)*60000))}
export function initWorkspaceOptions(){applyTheme();const o=new MutationObserver(()=>{blank();categoryView();settingsUI();layoutUI();applyLayout()});o.observe(document.body,{subtree:true,childList:true});document.addEventListener('input',e=>{if(e.target.closest?.('#ss-workspace'))queueSave()},true);document.addEventListener('change',e=>{if(e.target.closest?.('#ss-workspace'))queueSave()},true);document.addEventListener('click',e=>{tableDelete(e);if(e.target.closest?.('[data-ribbon="layout"]'))setTimeout(layoutUI,0)},true);document.addEventListener('keydown',e=>{if((e.key==='Delete'||e.key==='Backspace')&&document.activeElement?.closest?.('.ss-editor-table')){if(confirm('Delete this table?')){document.activeElement.closest('.ss-editor-table').remove();e.preventDefault()}}},true)}
