import { getCurrentDocument } from './document.js';
import { saveProject } from './filesystem.js';
import { createFontPicker } from './font-picker.js';
const SETTINGS_KEY='scriptsmith-settings-v2',LAYOUT_KEY='scriptsmith-layout-v1';
const PAPERS={Letter:['8.5in','11in'],A4:['8.27in','11.69in'],A5:['5.83in','8.27in'],Legal:['8.5in','14in'],Executive:['7.25in','10.5in'],'5 × 8':['5in','8in'],'5.25 × 8':['5.25in','8in'],'6 × 9':['6in','9in'],'7 × 10':['7in','10in']};
const MARGINS={Normal:['1in','1in','1in','1in'],Narrow:['.5in','.5in','.5in','.5in'],Moderate:['1in','.75in','1in','.75in'],Wide:['1in','2in','1in','2in']};
const defaults=()=>({autosave:true,autosaveInterval:10,theme:'modern',themeFont:'Inter'});
function settings(){try{return {...defaults(),...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch{return defaults()}}
function write(s){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify({...defaults(),...s}))}catch(_) {}}
function applyTheme(){const s=settings();document.body.classList.toggle('ss-theme-classic',s.theme==='classic');document.body.classList.toggle('ss-theme-modern',s.theme!=='classic');document.documentElement.style.setProperty('--ss-editor-font',`'${String(s.themeFont||'Inter').replace(/'/g,"\\'")}'`)}
function layout(){try{return JSON.parse(localStorage.getItem(LAYOUT_KEY)||'{}')}catch{return {}}}
function applyLayout(){const p=document.querySelector('#ss-pages');if(!p)return;const s=layout(),paper=PAPERS[s.paper]||PAPERS.Letter,m=MARGINS[s.margin]||MARGINS.Normal;p.style.setProperty('--ss-page-width',paper[0]);p.style.setProperty('--ss-page-height',paper[1]);p.style.setProperty('--ss-margin-top',m[0]);p.style.setProperty('--ss-margin-right',m[1]);p.style.setProperty('--ss-margin-bottom',m[2]);p.style.setProperty('--ss-margin-left',m[3]);p.style.setProperty('--ss-gutter',(s.gutter||0)+'in');p.style.setProperty('--ss-columns',(s.columns||1)>1?s.columns:'auto');p.classList.toggle('ss-landscape',s.orientation==='landscape');p.classList.toggle('ss-book-fold',!!s.bookFold)}
function blank(){const a=document.querySelector('.ss-library-actions');if(!a||a.querySelector('.ss-blank-document-button'))return;const b=document.createElement('button');b.className='ss-button ss-blank-document-button';b.textContent='Blank Document';b.onclick=()=>a.querySelector('[data-action="new"]')?.click();a.appendChild(b)}
function categoryView(){const h=document.querySelector('#ss-project-heading'),g=document.querySelector('#ss-project-grid');if(!h||!g)return;const main=h.textContent.trim()==='All Manuscripts';g.querySelectorAll('.ss-project-card').forEach(x=>x.style.display=main?'none':'')}
function settingsUI(){const m=document.querySelector('.ss-modal');if(!m||m.querySelector('.ss-settings-extra'))return;const s=settings(),x=document.createElement('section');x.className='ss-settings-extra';x.innerHTML=`<h3>ScriptSmith Preferences</h3><div class="ss-settings-field"><label>Theme<select id="ss-theme-choice"><option value="modern">Modern ScriptSmith</option><option value="classic">Classic Scriptorium</option></select></label></div><div class="ss-settings-field"><label>Theme Font<span id="ss-font-choice-slot"></span></label></div><div class="ss-settings-field"><label>Save interval<select id="ss-autosave-choice"><option value="1">1 minute</option><option value="5">5 minutes</option><option value="10">10 minutes</option><option value="15">15 minutes</option><option value="30">30 minutes</option></select></label></div>`;m.appendChild(x);const t=x.querySelector('#ss-theme-choice'),i=x.querySelector('#ss-autosave-choice');t.value=s.theme;i.value=String(s.autosaveInterval);const fc=x.querySelector('#ss-font-choice-slot');if(fc)fc.replaceChildren(createFontPicker({current:s.themeFont||'Inter',onPick:v=>{const q=settings();q.themeFont=v;write(q);applyTheme();const editor=document.querySelector('.ss-page-content');if(editor)editor.style.fontFamily=`'${v.replace(/'/g,"\\'")}'`}}));t.onchange=()=>{const q=settings();q.theme=t.value;write(q);applyTheme()};i.onchange=()=>{const q=settings();q.autosaveInterval=Number(i.value);q.autosave=true;write(q)}}
function layoutUI(){const c=document.querySelector('#ss-ribbon-content');if(!c||!document.querySelector('[data-ribbon="layout"].active')||c.querySelector('.ss-layout-controls'))return;const s=layout(),g=document.createElement('div');g.className='ss-ribbon-group';g.innerHTML=`<b>Page Layout</b><div class="ss-layout-controls"><label>Paper<select id="ss-paper">${Object.keys(PAPERS).map(x=>`<option>${x}</option>`).join('')}</select></label><label>Margins<select id="ss-margin">${Object.keys(MARGINS).map(x=>`<option>${x}</option>`).join('')}</select></label><label>Orientation<select id="ss-orientation"><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label><label>Columns<select id="ss-columns"><option>1</option><option>2</option><option>3</option></select></label><label>Gutter<input id="ss-gutter" type="number" min="0" max="3" step=".05"></label><label>Book fold<input id="ss-book" type="checkbox"></label></div>`;c.appendChild(g);const p=g.querySelector('#ss-paper'),m=g.querySelector('#ss-margin'),o=g.querySelector('#ss-orientation'),n=g.querySelector('#ss-columns'),u=g.querySelector('#ss-gutter'),b=g.querySelector('#ss-book');p.value=s.paper||'Letter';m.value=s.margin||'Normal';o.value=s.orientation||'portrait';n.value=String(s.columns||1);u.value=s.gutter||0;b.checked=!!s.bookFold;const update=()=>{try{localStorage.setItem(LAYOUT_KEY,JSON.stringify({paper:p.value,margin:m.value,orientation:o.value,columns:Number(n.value),gutter:Number(u.value||0),bookFold:b.checked}))}catch(_){}applyLayout()};[p,m,o,n,u,b].forEach(e=>e.addEventListener('change',update));applyLayout()}
function tableDelete(e){const t=e.target.closest?.('.ss-editor-table');if(!t)return;document.querySelector('.ss-table-delete')?.remove();const b=document.createElement('button');b.className='ss-table-delete';b.textContent='Delete table';b.type='button';b.onclick=()=>{t.remove();b.remove()};const r=t.getBoundingClientRect();b.style.left=`${r.right-90}px`;b.style.top=`${r.top-32}px`;document.body.appendChild(b);setTimeout(()=>b.remove(),5000)}
let timer=null;function queueSave(){const w=document.querySelector('#ss-workspace'),d=getCurrentDocument(),s=settings();if(!w||w.hidden||!d||!d.metadata?.libraryCategory||!s.autosave)return;clearTimeout(timer);timer=setTimeout(async()=>{try{await saveProject(d);const z=document.querySelector('#ss-save-status');if(z)z.textContent='Saved'}catch{}},Math.max(500,Number(s.autosaveInterval||10)*60000))}
export function initWorkspaceOptions(){applyTheme();const o=new MutationObserver(()=>{blank();categoryView();settingsUI();layoutUI();applyLayout()});o.observe(document.body,{subtree:true,childList:true});document.addEventListener('input',e=>{if(e.target.closest?.('#ss-workspace'))queueSave()},true);document.addEventListener('change',e=>{if(e.target.closest?.('#ss-workspace'))queueSave()},true);document.addEventListener('click',e=>{tableDelete(e);if(e.target.closest?.('[data-ribbon="layout"]'))setTimeout(layoutUI,0)},true);document.addEventListener('keydown',e=>{if((e.key==='Delete'||e.key==='Backspace')&&document.activeElement?.closest?.('.ss-editor-table')){if(confirm('Delete this table?')){document.activeElement.closest('.ss-editor-table').remove();e.preventDefault()}}},true)}
